### ISSUE TITLE
systemd without dbus

### ISSUE THREAD

**Issue by brechsteiner** [aelsabbahy/goss#101]
It should be possible to use the service resource on a systemd distro like debian without dbus.

**Comment by aelsabbahy** [comment]
Debian has systemd without dbus? Which version of debian? I would like to try to reproduce this locally so I can test a fix.

**Comment by brechsteiner** [comment]
Yes if you install the minimal installation, what is just normal in a productive server environment.
OS: Debian GNU/Linux 8.5 (jessie)

**Comment by aelsabbahy** [comment]
Thanks, I was able to reproduce this. I had incorrectly thought that systemd requires dbus, which I guess isn't the case.

The fix will probably be abandoning go-systemd in favor of just executing the systemctl command.

Thanks for filing this.

**Comment by aelsabbahy** [comment]
Fixed in [v0.1.8](https://github.com/aelsabbahy/goss/releases/tag/v0.1.8)
