### ISSUE TITLE
goupx is causing errors on some systems

### ISSUE THREAD

**Issue by aelsabbahy** [aelsabbahy/goss#106]
On some systems goss fails with the following error:
```
$ goss --help   
PROT_EXEC|PROT_WRITE failed.
```

Need to drop goupx. Was hoping to wait for Golang 1.7 to drop goupx, but since this is causing errors.. It should be done ASAP.

**Comment by aelsabbahy** [comment]
Fixed in [v0.1.9](https://github.com/aelsabbahy/goss/releases/tag/v0.1.9)

**Comment by aelsabbahy** [comment]
@marshyski  Noticed you thumbs up'd this, did you experience the same error? If so, were you running grsecurity Linux or selinux?

I didn't fully track down what was causing the issue, but UPX needed to be dropped anyways.

**Comment by marshyski** [comment]
@aelsabbahy No I haven't had a problem. Just supporting the changes coming from Go 1.7.  I am going to be using this at work, so if I run into any issues I'll contrib or file.

**Comment by aelsabbahy** [comment]
Gotcha, thanks.
