### ISSUE TITLE
debian jessie systemd is-enabled for service without unit file

### ISSUE THREAD

**Issue by brechsteiner** [aelsabbahy/goss#109]
The service enabled function on services without systemd unit files is not working correct.

OS: Debian 8.5
goss: v0.1.8

root@test01-01:~# service --status-all | grep ntp
 [ + ]  ntp
root@test01-01:~# goss add service ntp
Adding Service to './goss.yaml':

ntp:
  enabled: false
  running: true

**Comment by aelsabbahy** [comment]
Hmm.. so goss at the start of a run determines if a system is using systemd, upstart, or init and does its tests based on that detection.

So Debian is using both systemd and init side by side? I'm assuming `systemctl is-enabled ntp` returns false, right?

**Comment by brechsteiner** [comment]
A few service has already a new systemd unit file, but the most of it has just the old init files. 

root@test01-01:~#  systemctl is-enabled ntp
Failed to get unit file state for ntp.service: No such file or directory
root@test01-01:~# echo $?
1

**Comment by philpep** [comment]
Yes, this should be fixed in next debian release: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=760616

As a workaround I fallback to SysV in testinfra: https://github.com/philpep/testinfra/blob/master/testinfra/modules/service.py#L103

**Comment by aelsabbahy** [comment]
@philpep Yup, that's what I had to do for upstart, the fix for this will be very similar:
* https://github.com/aelsabbahy/goss/blob/master/system/service_upstart.go#L51

BTW, testinfra is awesome. That and serverspec were a great inspiration when I started writing goss :)

**Comment by aelsabbahy** [comment]
Fixed in [v0.1.9](https://github.com/aelsabbahy/goss/releases/tag/v0.1.9)

**Comment by brechsteiner** [comment]
cool, thanks for your fast reactions. Works great
