### ISSUE TITLE
Use as library without clicking context

### ISSUE THREAD

**Issue by vtolstov** [aelsabbahy/goss#112]
I want to use goss with packer.io but I don't think that I need additional dep for cli parsing.
Does it possible to use goss with another tool without cli.Context

**Comment by aelsabbahy** [comment]
It's been on my mental to do list but I haven't gotten around to it yet. Out of curiosity which part of goss are you looking to leverage got packer?

**Comment by vtolstov** [comment]
I want to write provisioner that checks builded running vm image with
precreated goss.yaml file and if all tests success, continue..

23 Июл 2016 г. 20:32 пользователь "Ahmed Elsabbahy" <
notifications@github.com> написал:

**Comment by aelsabbahy** [comment]
Ah, very cool.

I've marked this as a development facing enhancement, but I can't make any promises on when I'll be able to complete this ticket.

That said, I do wonder if leveraging the goss libraries directly for this could lead to a fragile implementation, ex: If I make a major refactor to goss.

Looking at the chef-solo provider, I wonder if a similar approach would be better and more resilient to goss internal changes? 
https://github.com/mitchellh/packer/blob/master/provisioner/chef-solo/provisioner.go

**Comment by vtolstov** [comment]
In case of chef-solo like you need to have binary installed,this is not
portable and can have some problems...
Does it possible to check external system via SSH for example?

23 Июл 2016 г. 20:48 пользователь "Ahmed Elsabbahy" <
notifications@github.com> написал:

**Comment by aelsabbahy** [comment]
goss only runs locally on the machine under test as it does not rely on external commands for most tests so no goss over ssh, unless you pipe the yaml file over ssh like `cat goss.yaml | ssh host 'goss validate`

You'd basically have to have the provisioner do the equivalent of this:
http://www.unixdaemon.net/puppet/puppet-integration-tests-in-seven-minutes/

OR have the goss library code somehow run directly in the machine under test.

**Comment by vtolstov** [comment]
Serverspec able to test via SSH as I know...
I'm try to fork and do some changes ,and recheck...

23 Июл 2016 г. 21:12 пользователь "Ahmed Elsabbahy" <
notifications@github.com> написал:

goss only runs locally on the machine under test as it does not rely on
external commands for most tests so no goss over ssh, unless you pipe the
yaml file over ssh like cat goss.yaml | ssh host 'goss validate

You'd basically have to have the provisioner do the equivalent of this:
http://www.unixdaemon.net/puppet/puppet-integration-tests-in-seven-minutes/

OR have the goss library code somehow run directly in the machine under
test.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/aelsabbahy/goss/issues/112#issuecomment-234732156>, or mute
the thread

**Comment by vtolstov** [comment]
After some checking, goss can handle external hosts via simple way:
you need to able to wrap util.NewCommand using ssh for example.
So if user specify target via ip:port to connect via go to that server via ssh and run provided command.

What do you think

**Comment by aelsabbahy** [comment]
The problem `goss` works differently than serverspec and testinfra in that it tries to rely as little as possible on external commands, this is how it's able to achieve extremely fast speeds, see [benchmarks](https://github.com/aelsabbahy/goss/wiki/Benchmarks)

Most checks don't use util.NewCommand, for example take a look at:
* https://github.com/aelsabbahy/goss/blob/master/system/file.go

The only ones that use external commands are the ones where I couldn't get around that limitation, services and packages basically.

**Comment by vtolstov** [comment]
Yes, i'm understand. but if this ability can exists, it will be fine =). thanks for help.
