### ISSUE TITLE
Run all tests in a directory.

### ISSUE THREAD

**Issue by apowers** [aelsabbahy/goss#14]
When validating a system it should run all tests in a given directory.
Many systems might share the same tests for something like ntpd and when I can symlink that test file into the directory for every system then I don't duplicate code.
 When I create a test file for each component of the system; ssh, postfix, snmpd, ntpd, nginx, etc.; the test files are easier to maintain.

**Comment by aelsabbahy** [comment]
Does `goss add goss` meet your needs?

Example:
```bash
$ goss -g goss_ssh.json autoadd sshd
Adding Group to 'goss_ssh.json':

{
    "sshd": {
        "exists": true,
        "gid": "74"
    }
}

Adding Process to 'goss_ssh.json':

{
    "sshd": {
        "running": true
    }
}

Adding Port to 'goss_ssh.json':

{
    "tcp6:22": {
        "listening": true,
        "ip": "0000:0000:0000:0000:0000:0000:0000:0000"
    }
}

Adding Port to 'goss_ssh.json':

{
    "tcp:22": {
        "listening": true,
        "ip": "0.0.0.0"
    }
}

Adding Service to 'goss_ssh.json':

{
    "sshd": {
        "enabled": true,
        "running": true
    }
}

Adding User to 'goss_ssh.json':

{
    "sshd": {
        "exists": true,
        "uid": "74",
        "gid": "74",
        "groups": [
            "sshd"
        ],
        "home": "/var/empty/sshd"
    }
}
```

```bash
$ goss -g role_sshd_server.json a goss ./goss_ssh.json
Adding Gossfile to 'role_sshd_server.json':

{
    "./goss_ssh.json": {}
}

$ cat role_sshd_server.json 
{
    "gossfile": {
        "./goss_ssh.json": {}
    }
}
```

```bash
$ goss -g role_sshd_server.json validate
..................

Total Duration: 0.014s
Count: 18, Failed: 0
```


See [goss add goss](https://github.com/aelsabbahy/goss#goss---add-a-goss-file-import) and [goss render](https://github.com/aelsabbahy/goss#render-r---render-gossfile-after-importing-all-referenced-gossfiles)

**Comment by apowers** [comment]
Yes, that looks like it would do the trick very nicely.
Interesting that the gossfile is an object of objects. What kind of data does the goss file-object support?

**Comment by aelsabbahy** [comment]
Currently, none. But I did it that way to:
A) Be consistent with all other resources
B) Allow for adding variable support in the future, allowing shared code to take parameters and such.
