### ISSUE TITLE
goss incorrectly reporting services as disabled

### ISSUE THREAD

**Issue by ashukaul** [aelsabbahy/goss#15]
Cool tool. but having issue on Ubuntu 12.04.4 LTS for service when trying to add although its enabled it think otherwise.   for e.g. 'autofs'

$ goss -g service.json a service autofs
Adding Service to 'service.json':
{
    "autofs": {
        "enabled": false,
        "running": true
    }
}

$ ls -l /etc/init.d/autofs
lrwxrwxrwx 1 root root 21 Oct  5  2012 /etc/init.d/autofs -> /lib/init/upstart-job

$ initctl show-config autofs
autofs
  start on runlevel [2345]
  stop on runlevel [!2345]

I am not sure whether this a "bug" or an enhancement request for the "upstart" but the upstart do have a backward compatibility   so keeping that open to you to decide. 

thanks!!

**Comment by aelsabbahy** [comment]
I've put off upstart support long enough.. I'll look into adding this.

**Comment by aelsabbahy** [comment]
Added upstart support in `v0.0.14`, let me know if you have any issues.

**Comment by aelsabbahy** [comment]
Actually, can you do me a favor and see that this works correctly when a job is disabled.. I took a guess as to how that's supposed to work, but I'm really not that well versed in Ubuntu.

**Comment by ashukaul** [comment]
yes, when I disabled a service via changing the value in /etc/init/autofs.service (for e.g.) i can see it got disabled. 

~# goss a service autofs
Adding Service to './goss.json':
{
    "autofs": {
        "enabled": false,
        "running": true
    }
}

But, when I stop the service  and then check it's still reflect as running 
# initctl stop autofs
autofs stop/waiting
 
# goss a service autofs
Adding Service to './goss.json':
{
    "autofs": {
        "enabled": false,
        "running": true
    }
}
which should not be the case. shouldn't  it be a different bug ?

**Comment by aelsabbahy** [comment]
Try `v0.0.15`, I incorrectly assumed Ubuntu followed this standard: http://refspecs.linuxbase.org/LSB_3.1.0/LSB-Core-generic/LSB-Core-generic/iniscrptact.html

Sorry for the inconvenience

**Comment by ashukaul** [comment]
Looks good.. !! now, both the boot status and current status looks good. 

 ~ service autofs stop
autofs stop/waiting
~ goss a service autofs
Adding Service to './goss.json':

{
    "autofs": {
        "enabled": true,
        "running": false
    }
}
