### ISSUE TITLE
Honor $GOSS_DST in install script when check installed version

### ISSUE THREAD

**Issue by santiagax99** [aelsabbahy/goss#151]
> echo "Downloading $url"
curl -L "https://github.com/aelsabbahy/goss/releases/download/$GOSS_VER/goss-linux-$arch" -o "$INSTALL_LOC"
chmod +rx "$INSTALL_LOC"
echo "Goss $GOSS_VER has been installed to $INSTALL_LOC"
echo "goss --version"
/usr/local/bin/goss --version
}

The last line of install.sh do not use $INSTALL_LOC and with key "set -e" install always return faulty code when passing GOSS_DST env var 

> $ curl -fsSL https://goss.rocks/install | GOSS_DST=~/app/bin sh
Downloading https://github.com/aelsabbahy/goss/releases/download/v0.2.3/goss-linux-amd64
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   589    0   589    0     0   1121      0 --:--:-- --:--:-- --:--:--  1119
100 6390k  100 6390k    0     0  2417k      0  0:00:02  0:00:02 --:--:-- 5808k
Goss v0.2.3 has been installed to /home/httpd/app/bin/goss
goss --version
sh: line 26: /usr/local/bin/goss: No such file or directory
$ echo $?
1

**Comment by aelsabbahy** [comment]
Should be fixed now, let me know if the issue still persists.
