### ISSUE TITLE
Format flag for add and autoadd

### ISSUE THREAD

**Issue by CMeza99** [aelsabbahy/goss#157]
Right now if I do an autoadd sometimes is in YAML and other times in JSON (but always has the yaml extension). I think, if the user can control the format, that would be the best.

**Comment by aelsabbahy** [comment]
Hmm, I've seen this before, but haven't been able to consistently reproduce. If you know a way to reproduce this let me know. Does specifying `goss -g goss.yaml add/autoadd` force it into YAML mode for you?

**Comment by CMeza99** [comment]
`-g file.(yaml|json)` will format the output accordingly if it is a new file (which is awesome, is this documented?).

So I think I found what was happening to me. If `add` or `aa` has nothing to return, a file with `{}` get created. Any subsequent `add`s or `autoadd`s will be in JSON, regardless of `-g`. I noticed then when I attempted `goss -g apache.yaml aa apache` (which is incorrect for Ubuntu 14.04). Then I did `goss -g apache.yaml aa apache2` and it was JSON.

**Comment by pysysops** [comment]
The suggested edit above (latest commit) is good for #173 and avoids an extra few CPU cycles of hitting setStoreFormatFromData when StoreFormat is already set. 

However a quick test of a non-existent resource in a new file still outputs an evil nil JSON object aka: `{}`

I'm kinda thinking here that a quick test for an empty resource before writing the file and printing a message and not an writing an empty file? 

What do you think?

**Comment by pysysops** [comment]
Good spot @CMeza99 I could reproduce it every time. If the file doesn't exist and you add / autoadd a resource that doesn't exist you get a file with `{}` in. I've created a PR that tackles this and another issue but would appreciate your feedback to add some context around how you're using goss. 

The PR checks if the resulting config is empty, notifies the user that the configuration is empty and **doesn't** create a file however, I'm not sure if this behaviour would cause a problem (missing file) for your use-case, it might be better to create an empty file appropriately: 

JSON:
```
{}
```
YAML:
```
---
```

What do you think?

**Comment by aelsabbahy** [comment]
@pysysops I could be wrong, but I believe the yaml driver in go writes an empty file as:
```yaml
{}
```

Which is valid YAML, but confusing. I don't think it's that big of an issue if subsequent adds are in the correct format. That said, I think the cleanest solution is not creating a file at all (your solution).
