### ISSUE TITLE
INI config validation/check

### ISSUE THREAD

**Issue by CMeza99** [aelsabbahy/goss#159]
It would be great to be able to check if a parameter does or does not exists. And if it does, being able to check that its value is correct.

If it's helpful here are Go projects for working with INI files:

- https://github.com/go-ini/ini
- https://github.com/alyu/configparser

And just fyi, here is how Salt does their YAML for INIs: https://docs.saltstack.com/en/latest/ref/states/all/salt.states.ini_manage.html

**Comment by aelsabbahy** [comment]
I think this is too specific, and there is a never ending set of config file formats out there to support. I would see if you can accomplish this with `command` instead combined with a simple script or command to extract parameters.

I'm following the 80/20 rule when it comes to adding functionality to goss, only tests that are pretty standard OS feature that would see wide use are built-in.
