### ISSUE TITLE
HTTP Redirects

### ISSUE THREAD

**Issue by CMeza99** [aelsabbahy/goss#160]
I am unable to use `http` to check for a `301` http code. It looks like the test is following the redirect. Perhaps an option to not follow redirects?

**Comment by aelsabbahy** [comment]
Agree, this would be a good enhancement.

**Comment by tdi** [comment]
@aelsabbahy I added reveresed boolean option `no-follow-redirects` in order not to break comptibility woth the previous versions. If you think that it is better to have `follow-redirects` then I can reverse and rebase. 

Please comment and review.
