### ISSUE TITLE
using multiple "command" calls only seems to validate the last one in the yaml file

### ISSUE THREAD

**Issue by MWake101** [aelsabbahy/goss#163]
I've got yaml file with multiple command checks (e.g. check the version returned by multiple installed products) but when I validate it only appears to check against the last commnd entry in the yaml file.

**Comment by MWake101** [comment]
Apologies, an error on my part reading the syntax - all resolved now.

**Comment by aelsabbahy** [comment]
Cool, if you feel the documentation is not clear, feel free to submit pull requests with better verbiage.
