### ISSUE TITLE
Add tests for environment variables

### ISSUE THREAD

**Issue by mspiegel** [aelsabbahy/goss#164]
Is there any interest in adding tests that checked against environment variables? The test could check for the existence of the variable or check that the variable is a specific value. I know this request is a little strange and possibly not a good usage of goss. Since the other classes of tests are idempotent to which process is running the tests. The environment variable tests would have to make sure that the environment variables were populated before goss was run. It would still be a nice feature to have.

If there's an interest in this feature I can make an attempt at submitting a pull request.

**Comment by aelsabbahy** [comment]
I would accept a pull request on this feature. I had thought about it in the past as I see some benefit to having this test when using `goss` with docker, or when using `goss` to verify that pre-conditions are in-place before executing a service.

Take a look at `kernel-param` for reference.

**Comment by mspiegel** [comment]
Thanks! I'll try to work on it next week.

**Comment by aelsabbahy** [comment]
Cool, just a heads up, you'll need to use genny and run `make gen` when modifying the resource list.

Apologies in advance for the bad code. Not sure if it's my amateur Golangism or if it's a consequence of no generics.

**Comment by mspiegel** [comment]
I'm getting an error when I run "make deps"
```
[ERROR]	Failed to set version on github.com/docker/docker to 0f5c9d301b9b1cca66b3ea0f9dec3b5317d3686d: Unable to update checked out version
```

**Comment by aelsabbahy** [comment]
Just tested it with glide v0.12.2 and it worked. travis-ci is using `0.10.2` which was working.

What version of glide do you have? Any chance its an intermittent issue?

**Comment by mspiegel** [comment]
Tried again this morning. Checked out a clean version and got off the VPN. "make deps" returns the same error.

**Comment by aelsabbahy** [comment]
It looks like the `glide` code that's throwing the error is here: https://github.com/Masterminds/glide/blob/3895d9e41edbe9186d65c9dde9c38148d9bbd49c/vendor/github.com/Masterminds/vcs/git.go#L134

I would try to:
```
# from the goss checked out folder
cd vendor/github.com/docker/docker
git fetch origin
```

And see what that says, depending on the output, maybe nuke away the `vendor/` folder all together and try running glide again? My guess is that it's either a weird `glide` issue, a network problem or corrupt `vendor/` dir?

Hope that helps.

**Comment by bryanlatten** [comment]
Looking forward to this work @mspiegel - can I make a feature request within your feature request? It would be great if I could use environment variables within my tests. For example, instead of saying 
```
file:
  /lib/path/to/something/config:
    exists: true
```

I would write: 

```
file:
   ${LIBPATH}:
     exists: true
```

I do use (and promote!) this heavily within a Docker environment. Happy to help review too

**Comment by twhiston** [comment]
I've made a PR with an initial version of an Environment Variable resource type, #306. It only addresses the original request for capturing and checking variable values, and not the request above, as this seemed in a slightly different scope (great idea though)

**Comment by aelsabbahy** [comment]
@bryanlatten 
> Looking forward to this work @mspiegel - can I make a feature request within your feature request? It would be great if I could use environment variables within my tests. For example, instead of saying

This is currnetly handled by the [template](https://github.com/aelsabbahy/goss/blob/master/docs/manual.md#templates) support:

You should be able to do something like:
```yaml
file:                                                                                                                                                                                         
  {{ .Env.LIBPATH }}:
    exists: true
```

@twhiston The PR looks to be on the right track so far.

**Comment by bryanlatten** [comment]
@aelsabbahy sorry for the (large) delay, your comment works perfectly as expected. thank you!
