### ISSUE TITLE
serve not updating port.tcp:

### ISSUE THREAD

**Issue by santiagax99** [aelsabbahy/goss#166]
Hi,

if goss runs in serve mode - "port" checks not updating if opened port state is changed, but other other checks updates properly ("file" in my case below)

env:
OS: CentOS7
Goss version: v0.2.4
$ cat goss.yaml
file:
    ~/test.txt:
        exists: true
        contains:
            - aaa
port:
    tcp:9001:
        listening: True

$ echo aaa > ~/test.txt; echo "Opened ports 9001";sudo netstat -tupan | grep 9001 ;echo "Running Goss"; curl 127.0.0.1:8080/healthz; uwsgi_manage.sh stop;sleep 5;echo bbb > ~/test.txt; echo "Opened ports 9001";sudo netstat -tupan | grep 9001 ;echo "Running Goss"; curl 127.0.0.1:8080/healthz;
Opened ports 9001
tcp        0      0 127.0.0.1:9001     0.0.0.0:\*               LISTEN      19638/python3.5
Running Goss
...

Total Duration: 0.016s
Count: 3, Failed: 0, Skipped: 0
gunicorn STOPPED
Opened ports 9001
Running Goss
..F

Failures/Skipped:

File: ~/test.txt: contains: patterns not found: [aaa]

Total Duration: 0.000s
Count: 3, Failed: 1, Skipped: 0

$ goss -g goss.yaml s -c 1s
2016/10/25 17:54:40 Starting to listen on: :8080
2016/10/25 17:54:51 127.0.0.1:14402: requesting health probe
2016/10/25 17:54:51 127.0.0.1:14402: Stale cache, running tests
2016/10/25 17:54:57 127.0.0.1:14403: requesting health probe
2016/10/25 17:54:57 127.0.0.1:14403: Stale cache, running tests

**Comment by aelsabbahy** [comment]
Was able to reproduce, this affects both ports and process checks. The cache needs to be reset when running tests.

I'll try to get a fix out within the week.
