### ISSUE TITLE
Add a resource for checking cronjobs.

### ISSUE THREAD

**Issue by lowks** [aelsabbahy/goss#172]
Add a resource for checking cronjobs.

**Comment by tdi** [comment]
Do you mean existence of a cronjob definition? I think here we need to consider user cronjobs and global cronjobs + different OS approach to splitting config file for the global cronjobs.

**Comment by lowks** [comment]
@tdi yes. As in a user has what kind or how many cronjobs under them

**Comment by aelsabbahy** [comment]
For now I think the combination of command and file resource can handle this today.

The concerns @tdi brings up make me hesitate to make this a dedicated goss resource for now.

**Comment by tdi** [comment]
Same opinion here, if it can be handled by a combination of resources, keep it that way, as long as it is not used super often. Unix approach, small things, doing jobs well.
