### ISSUE TITLE
How to properly check iptables rules?

### ISSUE THREAD

**Issue by taurus-forever** [aelsabbahy/goss#179]
Hi,

We have a problem with checking active iptables rules using goss on Debian Jessie.
We need to check:
 1) list of all expected active rules, e.g.: goss add command "iptables -S"
 2) ensure there are no more other/unexpected rules exist.  As there is no "count" for "command" stderr/stdout check we have to call iptables second time, like: goss add command "iptables -S | wc -l"

And here the problems appears here as iptables cannot be called in parallel at all, it produces different/random errors depending on order in yaml file "1) 2)" or "2) 1)" above.

Example:
```
root@myhost:~# rm /tmp/goss.yaml 
root@myhost:~# /usr/bin/goss_0.2.4 -g /tmp/goss.yaml add command "iptables -S"
Adding Command to '/tmp/goss.yaml':

iptables -S:
  exit-status: 0
  stdout:
  - -P INPUT ACCEPT
  - -P FORWARD ACCEPT
  - -P OUTPUT ACCEPT
  stderr: []
  timeout: 10000


root@myhost:~# /usr/bin/goss_0.2.4 -g /tmp/goss.yaml v
..

Total Duration: 0.003s
Count: 2, Failed: 0, Skipped: 0

root@myhost:~# /usr/bin/goss_0.2.4 -g /tmp/goss.yaml add command "iptables -S | wc -l"
Adding Command to '/tmp/goss.yaml':

iptables -S | wc -l:
  exit-status: 0
  stdout:
  - "3"
  stderr: []
  timeout: 10000


root@myhost:~# /usr/bin/goss_0.2.4 -g /tmp/goss.yaml v
....

Total Duration: 0.004s
Count: 4, Failed: 0, Skipped: 0

root@myhost:~# /usr/bin/goss_0.2.4 -g /tmp/goss.yaml v
FF..

Failures/Skipped:

Command: iptables -S: exit-status:
Expected
    <int>: 4
to equal
    <int>: 0
Command: iptables -S: stdout: patterns not found: [-P INPUT ACCEPT, -P FORWARD ACCEPT, -P OUTPUT ACCEPT]

Total Duration: 0.003s
Count: 4, Failed: 2, Skipped: 0
root@myhost:~# 
```

It appears more often if you have huge list of rules. With 30-50+ it happens with 100% probability.
It is known iptables issue which is still not addressed very well (google find a lot of references about the issues here) and I believe you cannot handle it properly into goss either.

The simple workaround here is:
```
goss add command "iptables -S"
goss add command "sleep 1 && iptables -S | wc -l"
```
while is is slow and ugly by design.

So, maybe you can consider to add support of "count" to check lines count in stderr/stdout output for the "command" action? Then we need to call iptables only once.

P.S. other ideas are welcome!

**Comment by aelsabbahy** [comment]
Count would be a nice feature that makes this much cleaner.

`P.S. other ideas are welcome!`

Here's a very hackish approach:
```
goss a command 'bash -c "iptables -S | tee >(echo lines: \$(wc -l))"'
```

Your goss.yaml would look something like this:
```yaml
command:
  'bash -c "iptables -S | tee >(echo lines: \$(wc -l))"':
    exit-status: 0
    stdout:
    - -P INPUT ACCEPT
    - 'lines: 106'
    stderr: []
    timeout: 10000
```

Not pretty, not sure I like it.. but iptables -S is executed only once. The exit status won't be accurate without more shell to capture it. (eww)

This might be a better approach.. This will run `iptables -S` twice, but doesn't need bash and should provide accurate exit status info:
```
goss a command 'iptables -S | echo lines: $(wc -l) && iptables -S'
```

I'm not exactly proud of either of those suggestions, but they'll get the job done.

**Comment by taurus-forever** [comment]
Thank you for the fast reply here!
We actually have it done using 'tee' approach, it just a bit faster.

Feel free to resolve the request or keep it open if consider adding 'count' to 'command'.

**Comment by aelsabbahy** [comment]
No problem, if you need proper exit-status you can use `pipefail`:

`goss a command 'bash -c "set -o pipefail;iptables -S | tee >(echo lines: \$(wc -l))"'`
 
I'll keep this open for now until I have a better description for the `count` feature, at that point I'll probably open a more targeted feature request.

Thanks for using/contributing to goss improvements! :+1:
