### ISSUE TITLE
Docker support

### ISSUE THREAD

**Issue by stephanbuys** [aelsabbahy/goss#18]
Hi,

I'm keen to build out extensive test suites for our infrastructure using goss. Its almost entirely Docker based, is Docker something you would be interested in adding? I'm think along the lines of

```
{
    "container": "/nginx/",
    "running": true,
    "created": true,
    "id": ....
}
```

Even possibly extending the `command` to run inside a container.

Regards,
Stephan

**Comment by aelsabbahy** [comment]
Docker support is something I am on the fence on. Part of me really wants to add it, part of me is wondering where the line should be drawn on what's supported by goss and what is pushed off to users using `command`.


For example:

```bash
$ cat goss.json
{
    "command": {
        "docker ps --format \"{{.Names}} {{.Status}}\"": {
            "exit-status": "0",
            "stdout": [
                "goss_int_test_precise Up",
                "goss_int_test_wheezy Up",
                "goss_int_test_centos6 Up"
            ],
            "stderr": []
        }
    }
}

$ goss validate
..

Total Duration: 0.025s
Count: 2, Failed: 0

$ docker stop goss_int_test_precise
goss_int_test_precise

$ goss validate
.F

Failures:
Command: docker ps --format "{{.Names}} {{.Status}}": stdout: patterns not found: [goss_int_test_precise Up]

Total Duration: 0.028s
Count: 2, Failed: 1
```

**Comment by stephanbuys** [comment]
Fair enough, trying to think it through a bit more, I guess a Docker command would make sense if you are interested in more info (like the parent image, the running time, the exit code, the container ID, etc?)

**Comment by aelsabbahy** [comment]
Has command worked out okay or have you found it lacking?

**Comment by stephanbuys** [comment]
Hi, we've been using command happily, so please feel free to close this issue.

**Comment by aelsabbahy** [comment]
Thanks for the update.
