### ISSUE TITLE
How to ensure stdout/stderr are empty or having empty lines output

### ISSUE THREAD

**Issue by taurus-forever** [aelsabbahy/goss#184]
Hi,

I might be blind, but I see no answer in manuals.
Sometimes you need to check that output of some command has only allowed labels, like
"something status" has multilines output with labels "up", "running", "whatever" only:
```
>> something status
> server 1 up
>
> service2 running
>
> blablabla whatever
```

In this case it is impossible to use "match" check, as amount of lines will be changes very offten.
The only things you know that "markers" for successful line are "up", "running", "whatever".
In this case goss test will looks like:
```
something status | grep  -Ev '^(\s+)?$|up|running|whatever' | wc -l:
  exit-status: 0
  stdout:
  - "0"
```

Problem: I do not like "wc -l" at the end. It is one more process to fire and pipe.
I just would like to ensure stdout/stderr are "empty".
How can I do this? Tried a lot of combinations described here https://github.com/aelsabbahy/goss/blob/master/docs/manual.md , no luck.
Any hints here?

P.S. maybe we need:
```
something status | grep  -Ev '^(\s+)?$|up|running|whatever':
  exit-status: 0
  stdout: NULL
  stderr: NULL
```

or even
```
something status:
  exit-status: 0
  ignore-lines:
    - ^(\s+)?
    - up
    - running
    - whatever
  stdout: NULL
  stderr: NULL
```

Tnx!

**Comment by aelsabbahy** [comment]
There's an unintuitive way to do this in goss that I show here: https://github.com/aelsabbahy/goss/issues/145#issuecomment-245045346

You can also use `something status | grep -qEv '...'` and check the exit-status on grep.

**Comment by taurus-forever** [comment]
Thank you for the hint with " stderr: ['!/./'] ". Unfortunately it still required grep -v "^(\s+)?$" to remove "empty" lines (which often happens in Linux tools).
" stderr: ['!/./'] " is better then nothing while less readable then wc -l. I will keep K.I.S.S. here.

Sure "exit code" is something I am checking already :-)
Feel free to resolve. Tnx for the hint!

**Comment by aelsabbahy** [comment]
Out of curiosity, for your first example using `stdout: NULL` were you thinking that would ignore newlines or not? I would think most "empty" output of linux commands is really `\n`

I'll close this issue out, for now since there's a workaround, but probably something I need to clean up in the future.

Thanks for using goss and providing feedback!
