### ISSUE TITLE
help mgmt config project out with tests!

### ISSUE THREAD

**Issue by purpleidea** [aelsabbahy/goss#187]
Hey! One of your fans pointed me to this project. I'm the main author of the https://github.com/purpleidea/mgmt/ project. It's a next generation config management project and is still pre-prod. We'd love to have your library be used for testing our resources! This could help improve the robustness of our project, and get you a big user.

If you're interested, and want to send some patches our way, please let me know...

**Comment by aelsabbahy** [comment]
I'll reach out to you sometime this week on IRC and we can discuss it further.

Love mgmt, I remember reading your blog post and watching your presentation on it a ~year back, some great concepts there.

**Comment by purpleidea** [comment]
> I'll reach out to you sometime this week on IRC and we can discuss it further.

@aelsabbahy Awesome! We're in #mgmtconfig on Freenode, and I'm purpleidea there of course.

> Love mgmt, I remember reading your blog post and watching your presentation on it a ~year back, some great concepts there.

Thanks! I'd like to think we've matured a lot since then, and still speeding up! More testing would be awesome :)

**Comment by purpleidea** [comment]
FYI: we fixed a lot of the native golang test infra so if you had previously looked and found that broken, our apologies and things are nicer now!

**Comment by aelsabbahy** [comment]
I've been swamped with a new client as of late, haven't had time to look into this. I'll try to reach out to you sometime this week on IRC to understand this better.

**Comment by purpleidea** [comment]
No rush just wanted to update you as I felt bad about the state previously. Good luck with your new client.
