### ISSUE TITLE
Windows support

### ISSUE THREAD

**Issue by petemounce** [aelsabbahy/goss#191]
Similarly to #26, it would be great to get Windows support. I assume since you welcomed PRs for FreeBSD, you might also welcome ones that add Windows support?

(Obviously, Windows being what it is, I expect this would require more work than FreeBSD... ;) ).

**Comment by JackLeo** [comment]
What are the missing bits given the existing PR?

**Comment by petemounce** [comment]
Packages (maybe via chocolatey)?

**Comment by JackLeo** [comment]
Something like this is more likely:

https://gallery.technet.microsoft.com/scriptcenter/Script-to-get-installed-80cd3798

by the looks of it - digging through the registry should produce the most universal results for base system

**Comment by petemounce** [comment]
I really can't recommend taking a dependency on anything written in VB. wmic probably has a longer deprecation horizon; VB is very legacy.

**Comment by JackLeo** [comment]
So it's either [wmic](https://msdn.microsoft.com/en-us/library/aa394531(v=vs.85).aspx) or [inline .NET](https://msdn.microsoft.com/en-us/library/microsoft.win32.registry.getvalue(v=vs.110).aspx?cs-save-lang=1&cs-lang=csharp#code-snippet-1) doing the query. For MVP I would suggest just calling wmic subprocess and retrieving the results then allow someone with deeper Windows knowledge to build further.

**Comment by petemounce** [comment]
Definitely wmic is the easiest bar, though won't detect portable apps installed via chocolatey. I'd say that's going to be an edge case for systems administration vs consumer users.

**Comment by petemounce** [comment]
Re: supported - wmi dates back a decade or so at least. Probably fine for the set of likely user population of this library.

**Comment by JackLeo** [comment]
wmic should detect anything installed via an installer since that puts uninstaller registry entry. Packages like Docker could be both installed via an installer and chocolatey so there might be some edge cases with using them both.

**Comment by petemounce** [comment]
Having come back to this, I'm now inclined to think that `package` should assert against package-manager installs only. If software is present on the machine, and the person wants to write tests to assert that, I bet they're _almost certainly_ already aware of chocolatey.

And, @JackLeo is entirely correct, it's possible for a thing to be installed via chocolatey and other means, to completely separate places.

Is it reasonable to make one (initial) chocolatey implementation, and one wmic-based? I saw there's [a `--format` argument to specify](https://github.com/aelsabbahy/goss/blob/master/docs/manual.md#package) which flavour...?

**Comment by JackLeo** [comment]
I would be inclined to suggest more of a salt approach. `package` should check _all default_ packaging methods. Any additional ones should be explicit. 

Example:
  * package - https://docs.saltstack.com/en/latest/ref/states/all/salt.states.pkg.html
  * pip - https://docs.saltstack.com/en/latest/ref/states/all/salt.states.pip_state.html

I do agree that `wmic` is not necessarily a packaging mechanism and it might need to be exposed as an explicit check/utility, however, I do not agree that `chocolatey` could be considered a _default_ method of install/packaging, equally I would not say `brew` is default one for mac purely based on the fact that is installed by the user and not shipped as part of the OS.

**Comment by estahn** [comment]
#349 should help with this.

**Comment by petemounce** [comment]
#380 is trying to add a Windows binary to the releases.

**Comment by videte47** [comment]
is this still active?

**Comment by aelsabbahy** [comment]
Goss now provides community supported alpha binaries for windows as per- #585
