### ISSUE TITLE
macOS support

### ISSUE THREAD

**Issue by petemounce** [aelsabbahy/goss#192]
Similarly to #26, it would be great to get macOS support. I assume since you welcomed PRs for FreeBSD, you might also welcome ones that add macOS support?

**Comment by brianantonelli** [comment]
Would love to see OSX support!

**Comment by aelsabbahy** [comment]
One point to clarify. Since Goss runs locally on the target machine. This enhancement would be for those interested in using Goss to validate a macos system.

dgoss should work just fine if the target docker is Linux.

**Comment by brianantonelli** [comment]
I have it compiling on OS X fine, but I get some errors when invoking it through dgoss.

**Comment by aelsabbahy** [comment]
To get it working on Mac:
```
# Install dgoss
curl -L https://raw.githubusercontent.com/aelsabbahy/goss/master/extras/dgoss/dgoss -o /usr/local/bin/dgoss
chmod +rx /usr/local/bin/dgoss

# Download goss to your preferred location
curl -L https://github.com/aelsabbahy/goss/releases/download/v0.3.1/goss-linux-amd64 - o ~/Downloads/goss-linux-amd64

# Set your GOSS_PATH to the above location
export GOSS_PATH=~/Downloads/goss-linux-amd64

# Use dgoss
dgoss edit ...
dgoss run ...
```

**Comment by aelsabbahy** [comment]
I've updated the `dgoss` readme with [Mac installation instructions](https://github.com/aelsabbahy/goss/tree/master/extras/dgoss#mac-osx)

**Comment by twhiston** [comment]
So what additionally would be needed to validate an OSX install? (ie use goss for mac rather than from mac) maybe we could use homebrew for the package checking (as most automation I have seen uses homebrew to install/validate things, ie ansible), what other items do we need to deal with? i'd be really willing to work on this if we can break the task down into well defined chunks.

**Comment by automaticgiant** [comment]
works fine for me. my use case is the http/dns/tcp stuff that i can use remotely to validate a terraform stack comes up. i stick it in a provisioner so it can bluegreen r53 only if the stack starts taking traffic correctly. this is a killer use case as it has the waiting/timeout stuff. i just would like the binaries added to releases.

**Comment by estahn** [comment]
#349 should help with this.

**Comment by petemounce** [comment]
#380 is trying to add macOS binaries to the releases.

**Comment by SpokeyWheeler** [comment]
Another request for macOS binaries, please!

**Comment by ssbarnea** [comment]
... no progress so far, starting to loose hope.

**Comment by aelsabbahy** [comment]
Community supported macOS alpha binaries are now part of a goss release, see #585
