### ISSUE TITLE
Add timeout parameter to `command`

### ISSUE THREAD

**Issue by aelsabbahy** [aelsabbahy/goss#20]
command should have a timeout parameter, similar to dns and addr lookups #19

**Comment by aelsabbahy** [comment]
Initial idea:

```bash
# default timeout is 10s
$ goss a command 'sleep 1;echo "hi"'
Adding Command to './goss.json':

{
    "sleep 1;echo \"hi\"": {
        "exit-status": "0",
        "stdout": [
            "hi"
        ],
        "stderr": [],
        "timeout": 10000
    }
}

# Happy path
$ goss validate
..

Total Duration: 1.011s
Count: 2, Failed: 0


$ sed -i 's/sleep 1/sleep 11/' goss.json

# Command took too long
$ goss validate
FF

Failures:
sleep 11;echo "hi": exit-status: Error: Command execution timed out (10000 milliseconds)
sleep 11;echo "hi": stdout: Error: Command execution timed out (10000 milliseconds)

Total Duration: 10.007s
Count: 2, Failed: 2
```

@stephanbuys how does that look?

One drawback with current implementation is that `sleep 12` works when adding, but when you run `goss validate` it will fail unless you manually tweak the timeout to be more than 10000 milliseconds (default).

For now I think it's a minor inconvenience. In the future, I'll probably revamp the timeout to be dynamically set based on maybe `1.5 * command_execution_time_during_add` and maybe change it to string format, so the JSON will support things like "10s". Or maybe something like `goss add command --timeout 1m 'sleep 12'`. But I'd like to hold off on that until I have a uniform answer for `command`, `addr` and `dns` for consistency.

**Comment by stephanbuys** [comment]
I like your last suggestion `goss add command --timeout 1m 'sleep 12'` - having a default timeout is probably going to surprise a whole lot of people.

**Comment by aelsabbahy** [comment]
This has been added to [v0.0.18](https://github.com/aelsabbahy/goss/releases/tag/v0.0.18)
