### ISSUE TITLE
Friends don't let friends pipe to sh

### ISSUE THREAD

**Issue by cruschke** [aelsabbahy/goss#202]
As explained for example [here](https://www.seancassidy.me/dont-pipe-to-your-shell.html) or [here](https://jordaneldredge.com/blog/one-way-curl-pipe-sh-install-scripts-can-be-dangerous/) installing something by `sudocurlbash` should be avoided.

[fpm](https://github.com/jordansissel/fpm) is a tool for building almost any sort of package (rpm, deb, apk, ...), if you would also build packages one could do a `yum install http://url/to/goss.rpm` .

**Comment by CMeza99** [comment]
Yes, `curl | sh` is horrible, but I do not believe that Goss needs to be a package. Part of what I like about it is the ability to drop the binary where I need it. My use cases include things like system testing in CI/CD.

**Comment by aelsabbahy** [comment]
I'm not a huge fan of `curl | sh` either, but there's nothing stopping users from using the [manual-installation](https://github.com/aelsabbahy/goss#manual-installation) instructions. Tools that automatically install goss (ex. molecule, kitchen-goss, etc.) are all using to the manual method to my knowledge (as they should).

The `curl | sh` is provided as a convenience for those that don't mind it.

That said, I've made some attempts to make `curl | sh` a little more secure:
* Using https/SSL to prevent man in the middle
* Lines [#3](https://github.com/aelsabbahy/goss/blob/master/install.sh#L3) and [#27](https://github.com/aelsabbahy/goss/blob/master/install.sh#L27) to protect against partial download issue described in your first link 

There is of course a risk if https://goss.rocks gets compromised. Tools like [hashpipe](https://github.com/jbenet/hashpipe) and others can be leveraged to fix this.. But honestly, at that point it's best to just do the manual install than to over engineer the `curl | sh` solution with more dependencies.

fpm is nice, but not something I want to maintain, especially given that the manual instructions are two simple commands.

**Comment by aelsabbahy** [comment]
I'll leave this issue open, until update the readme with a small note to warn users not to use `curl | sh` in production.

**Comment by cruschke** [comment]
I am fine with highlighting the potential risk in the readme. 👍

**Comment by aelsabbahy** [comment]
Updated readme. Thanks!
