### ISSUE TITLE
Can goss check file owner from LDAP?

### ISSUE THREAD

**Issue by taurus-forever** [aelsabbahy/goss#205]
HI,

I was surprised here while it looks like it cannot:
```
Failures/Skipped:

/somefile: owner: Error: no matching entries in passwd file

Total Duration: 0.128s
Count: 121, Failed: 1, Skipped: 0

me@somewhere42:~$ ls -la /somefile
-rw-r----- 1 testuser root 106 Mar 14 12:25 /somefile

me@somewhere42:~$ id testuser
uid=10021(testuser) gid=10000(testgroup) groups=10000(testgroup)
```

I believe it is expected here as "goss add" doesn't add LDAP user to check, I added it manually.
So the ticket here is a question: "Any plans/ideas to support LDAP?" :-)

**Comment by aelsabbahy** [comment]
How did you add the user manually, I'm curious?

So if a file is owned by an ldap user the file ownership check is failing?

**Comment by taurus-forever** [comment]
Yes, I have added it manually.
With YAML it is easy to write tests ;-)

As I wrote, command "goss add file" doesn't add "owner" here. So I decided
goss doesn't work with LDAP by design.

WBR, Alex

**Comment by aelsabbahy** [comment]
Ah, so added manually, but validate fails with the above error.

I'll keep this open for now, but haven't put much thought into how to best solve this, or whether Goss should.

**Comment by aelsabbahy** [comment]
Can you do me a favor and test the binary I've attached here: [goss.zip](https://github.com/aelsabbahy/goss/files/857001/goss.zip)

I compiled it locally on my machine from #210, feel free to compile that branch from source if you don't trust a local build from me.

Basically, I'm using `getent passwd <uid>` and `getent group <gid>` as fallbacks if the user doesn't exist in `/etc/{passwd,group}`. If it's found in neither, the error message will be a concatenated message from both attempts at looking up the user, example:
```
/tmp/test: owner: Error: Error: no matching entries in passwd file. getent passwd: exit status 2
/tmp/test: group: Error: Error: no matching entries in passwd file. getent group: exit status 2
```

**Comment by taurus-forever** [comment]
Tested goss.zip, it does the job perfectly.
Also "./goss-linux-amd64 -g ./test.yaml add file ./test_file" works like a charm!
Thank you, waiting for the release here.

**Comment by taurus-forever** [comment]
Any chances to have LDAP support released anytime soon? Tnx!

**Comment by aelsabbahy** [comment]
Yeah, will go out by the end of the week. I was on vacation.

Also, to be clear this is only for the file resource. The user resource doesn't support ldap yet.
