### ISSUE TITLE
Redirect output to distant repo

### ISSUE THREAD

**Issue by adeleglise** [aelsabbahy/goss#207]
HI,

First of all, thanks a lot for this great piece of software ! It works like a charm and it's **really** fast ;)

I'm currently using it with jenkins and testlink to automate infrastructure tests.

The problem is the generated output sits on the server where goss is executed, obviously. I'm looking for a way to sent the generated results in TAP format in the jenkins workspace repo.

Do you have an idea on how to do it ?

**Comment by aya** [comment]
You may want to use ansible plugin for jenkins : https://wiki.jenkins-ci.org/display/JENKINS/Ansible+Plugin to run your tests.

**Comment by adeleglise** [comment]
Ok, i will try with ansible plugin.

Thanks.
