### ISSUE TITLE
wrong goss version on v0.3.1

### ISSUE THREAD

**Issue by shomodj** [aelsabbahy/goss#209]
building goss from source on tag v0.3.1 results in this

```
goss -v
goss version 0.0.0
```

**Comment by aelsabbahy** [comment]
Building from source is always 0.0.0  unless the "$TRAVIS_TAG" variable is set (Makefile). Or if you're using `go build`,  "-X main.version".


See:
* https://github.com/aelsabbahy/goss/blob/master/Makefile#L6
* https://github.com/aelsabbahy/goss/blob/master/Makefile#L43

**Comment by shomodj** [comment]
ah, thanks
