### ISSUE TITLE
ARM release

### ISSUE THREAD

**Issue by bamarni** [aelsabbahy/goss#211]
Would it be possible to have a release for linux arm? Thanks

**Comment by aelsabbahy** [comment]
I'm not as familiar with the ARM side of go.. I notice there's a bunch of versions of it:
https://github.com/golang/go/wiki/GoArm#supported-architectures

Are they backwards compatible or would this add 4 new binary releases?

**Comment by bamarni** [comment]
AFAIK they're pretty much backward compatible. I'm not that much familiar with the whole ARM ecosystem but ARMv5 seems very old, and was even considered for removal (https://github.com/golang/go/issues/17082).

I think a release with `GOARM=6	GOARCH=arm` should be fine for most ARM users.

**Comment by elfgoh** [comment]
@aelsabbahy I think it will work fine just to support the default ARM version, as [suggested by Dave Cheney](https://dave.cheney.net/2015/08/22/cross-compilation-with-go-1-5). Or at least until there is a huge demand for other ARM versions
