### ISSUE TITLE
Feature: Cloud Resource?

### ISSUE THREAD

**Issue by patran** [aelsabbahy/goss#234]
A cloud resource to query various clouds to validate:

1. Number of instances
1. Number of instances with a given tag, attributes (cpu, memory, disk, etc)
1. Dynamic inventory to feed the goss to validate all hosts in the inventory

Rather than 1 cloud resource per provided, it would great if an abstraction (provider?) could be provided to facilitate the addition of additional clouds, using their specific APIs.

**Comment by elliotweiser** [comment]
Perhaps I misunderstand your feature request, in which case I'd ask you to clarify.

Judging by your word-choice, it sounds like you're using some cloud provider along with Ansible and GOSS to do some kind of programmatic cloud automation/testing. Kudos!

The way I've seen GOSS typically used is to validate the state of a _particular server_ (instance, image, container, etc.), and not a whole cloud/cluster of them. GOSS executes within the "object" it is trying to validate and reports specifically about the state of that "object".  IMO, the idea of creating a "cloud" resource sounds like [feature creep](https://en.wikipedia.org/wiki/Feature_creep). To summarize, I think you're request is "out-of-scope".

That said, it's not a bad idea! If there's a genuine use-case for what you're proposing, then that sounds like the makings of an interesting project.
