### ISSUE TITLE
Printing the output of a bash script executed by a goss test

### ISSUE THREAD

**Issue by transcedentalia** [aelsabbahy/goss#243]
I have a goss test that is running a bash script. The bash script is printing some output with echo.  The output of the bash script is not visible in goss' output or anywhere in the console/terminal. 

Is it possible to see that output somehow? Browsing through the documentation I couldn't find anything helpful.

Thank you

**Comment by aelsabbahy** [comment]
Currently no, command output us treated like file content. Goss loops over it line by line and fails or succeeds depending on if it's found.

This would be an interesting feature request to evaluate if this is something you want.

**Comment by fracasula** [comment]
I think it'd be an interesting failure, especially when debugging failing tests. When that happens I'm forced to get into the container myself to run the failing tests manually. Something like a `--force-output` option to enable it on demand would be really nice I think.

:+1:

**Comment by aelsabbahy** [comment]
Being tracked here now: https://github.com/aelsabbahy/goss/issues/483
