### ISSUE TITLE
Copy goss instead of mounting it as a Docker volume

### ISSUE THREAD

**Issue by sandekar** [aelsabbahy/goss#246]
**What I am suggesting ?**
I took a look at the [dgoss](https://github.com/aelsabbahy/goss/blob/master/extras/dgoss/dgoss) script (more precisely the `run` function) and I think the volume mounting could easily be replaced with `docker cp` copying the goss binary inside the container right after starting it. I tested it and could contribute the change as PR if necessary.

**Why I'm suggesting this change ?** 
We have a development infrastructure based on Jenkins v2 + Jenkins slaves all running as Docker services. Due to this approach we need to run Docker in Docker in order to use it within the slaves for our pipelines (by mounting the socket). But we faced a problem with volume mounting in the slaves because the folder referenced in the `-v` argument is not actually in the slave, it's on the host and the slave service cannot see it (More on this [here](https://stackoverflow.com/questions/31381322/docker-in-docker-cannot-mount-volume)). And because the dgoss script is mounting the goss binary to execute tests, it is impossible to run them cause it's not in the mounted folder.

**Comment by aelsabbahy** [comment]
Makes sense, I didn't consider or test docker in docker when writing dgoss. Feel free to submit a pull request with a cp implementation.

If you need examples to test with, there's a few here: https://github.com/aelsabbahy/dgoss-examples

Also, I'd be curious to see the performance difference between mount and cp implementation.

**Comment by sandekar** [comment]
After running the examples I faced a problem with my suggestion. The dgoss script exposes the container log in the mounted volume and if I replace that I would brake existing tests that verify it. Possible workarounds:

- Copy the log before executing the tests - That would allow tests in goss.yaml to pass... but anything that checks the container output in goss_wait.yaml would not.
- Mount and copy - Mount the log and after container startup just copy the tests & binary in. This way no breaking changes will be introduced and it will allow tests to be executed in docker in docker BUT without being able to test against the container output.

I'm starting to think towards custom dgoss script just for my needs.

**Comment by armpogart** [comment]
I would also be interested in solution to run dgoss in docker in docker CI environment.

**Comment by mkobit** [comment]
As another 👍 , we do the Jenkins-builds-in-Docker so this would be incredibly useful

**Comment by elliotweiser** [comment]
I believe this issue will be addressed in #271, since it provides the ability to `cp` rather than mount the goss files in a volume.

**Comment by aelsabbahy** [comment]
Closed by #271 it's on the master branch now. I usually don't cut releases for dgoss changes, so it'll be on the github "releases" tab in the next release.
