### ISSUE TITLE
Single line json output

### ISSUE THREAD

**Issue by luisdavim** [aelsabbahy/goss#247]
Hi,

I'm using goss in a systemd timer and JournalBeat to ship the logs to ElasticSearch.
At the moment I'm using the nagios_verbose format and parsing it in logstash but if the json output was a single line json message I could use that directly with no need for parsing.

Can you make the json output format single line and maybe introduce a json_pretty that is multi line?

Thanks.

**Comment by aelsabbahy** [comment]
I would probably add a json_oneline to preserve backwards compatibility.

**Comment by luisdavim** [comment]
That would work as well.

**Comment by aelsabbahy** [comment]
Sorry, forgot about this when creating today's release. It'll be in the next version of goss.

**Comment by aelsabbahy** [comment]
Released in `v0.3.4`
