### ISSUE TITLE
Service Module on Sys V Init Doesn't Work Reliably

### ISSUE THREAD

**Issue by naftulikay** [aelsabbahy/goss#250]
It's not sure who's to blame here, most likely Docker, but I believe [there's a bug in this line of code](https://github.com/aelsabbahy/goss/blob/master/system/service_init.go#L55). 

Unfortunately, Docker's Sys V Init script doesn't return non-zero when the service is stopped:

```
root@5bd7ea8a9eb2:/# service docker status
docker stop/waiting
root@5bd7ea8a9eb2:/# echo $?
0
```

This basically causes my tests to fail.

**Comment by aelsabbahy** [comment]
```
If the status action is requested, the init script will return the following exit status codes.

0 | program is running or service is OK
-- | --
1 | program is dead and /var/run pid file exists
2 | program is dead and /var/lock lock file exists
3 | program is not running
4 | program or service status is unknown
5-99 | reserved for future LSB use
100-149 | reserved for distribution use
150-199 | reserved for application use
200-254 | reserved
```
http://refspecs.linuxbase.org/LSB_3.0.0/LSB-PDA/LSB-PDA/iniscrptact.html

The service seems to be behaving incorrectly to me.
