### ISSUE TITLE
How test a port on my container ? Please Help ME !

### ISSUE THREAD

**Issue by guiyomh** [aelsabbahy/goss#251]
Hi,

I don't understand why i cannot test a port on my container.
I have this :
```bash
/goss # netstat -pan 
Active Internet connections (servers and established)
Proto Recv-Q Send-Q Local Address           Foreign Address         State       PID/Program name    
tcp        0      0 :::9000                 :::*                    LISTEN      18/php-fpm.conf)
Active UNIX domain sockets (servers and established)
Proto RefCnt Flags       Type       State         I-Node PID/Program name    Path
unix  2      [ ACC ]     STREAM     LISTENING     1994948 1/python            /run/supervisord.sock.1
unix  3      [ ]         STREAM     CONNECTED     1996012 18/php-fpm.conf)    
unix  3      [ ]         STREAM     CONNECTED     1996013 18/php-fpm.conf)    
```
When i type `goss a port 9000` the output of the command is : 
```shell
/goss # goss a port 9000
Adding Port to './goss.yaml':

tcp:9000:
  listening: false
  ip: []
```
I edit the goss.yaml to modify the test like this :
```yaml
tcp:9000:
  listening: true
  ip: [0.0.0.0]
```
When i try to validate i have : 
```shell
/goss # goss validate
........................................F

Failures/Skipped:

Port: tcp:9000: listening:
Expected
    <bool>: false
to equal
    <bool>: true

Total Duration: 0.006s
Count: 41, Failed: 1, Skipped: 0
/goss # 
```

Why ?
Where my error ?

**Comment by elliotweiser** [comment]
Hey @guiyomh !

Judging by the output of `netstat`, that's an IPv6 listening socket. You're testing for the existence of an IPv4 listening socket. Though I don't think it's documented (yet), that should work if you change `tcp` to `tcp6`. 

```yaml
tcp6:9000:
  listening: true
  ip: ['::']
```

There are several examples among the integration tests for this project e.g.

https://github.com/aelsabbahy/goss/blob/12d355ae79a163c28c08bae00674db4048d3ecf3/integration-tests/goss/alpine3/goss.yaml#L21-L25

Alternatively, you could bind the listening server to the IPv4 address, and then you don't have to change your test. Hope this helps 😄

**Comment by aelsabbahy** [comment]
It has to do with this yet to be resolved issue:

https://github.com/aelsabbahy/goss/issues/149

Basically, goss doesn't support `net.ipv6.bindv6only` passthrough.

**Comment by elliotweiser** [comment]
@guiyomh Did my feedback address your issue?

**Comment by aelsabbahy** [comment]
I've updated the documentation to explain this better.
https://github.com/aelsabbahy/goss/blob/master/docs/manual.md#port

**Comment by guiyomh** [comment]
thx, it's good
