### ISSUE TITLE
Stabilizing the CI process

### ISSUE THREAD

**Issue by elliotweiser** [aelsabbahy/goss#253]
Some steps that could be taken for (further) stabilizing the CI process:

* Pin the version of the Docker base image under test
* Bake/use an intermediate parent image after `apt-get update` (or equivalent for package manager)

Certain integration tests check the version of installed packages (e.g. Apache) and this could help avoid forcing those updates into otherwise unrelated changes. I've encountered this several times when submitting PRs. Updating the images/packages under test would be relegated to changes intended for that purpose. Logical separation of what is being contributed/tested/reviewed is always nice for maintainers since changes should be _small_ and _to-the-point_.

This is just food for thought.

**Comment by aelsabbahy** [comment]
I had an initial attempt at this.

See:
* https://github.com/aelsabbahy/goss/blob/master/integration-tests/test.sh#L19
* And the scripts in the development folder.

Was based on the md5sum of the docker file.

The main issue is, given enough time the package no longer exists on the official repos.

**Comment by aelsabbahy** [comment]
Side note, thanks for all your contributions so far. Much appreciated!

**Comment by elliotweiser** [comment]
I think I understand the mechanics of that now. I'd say that's probably "good enough". This is the unfortunate reality of integration testing in general.

In my particular case (i.e. all the wheezy apache package updates), it's at the mercy of the external apt repository. I wonder if it's worth using a different package as a guinea pig on wheezy. This is assuming that said package's version/release management is more sane and earlier releases aren't completely obliterated. 

> Side note, thanks for all your contributions so far. Much appreciated!

I'm a fan of the project! It's my pleasure.
