### ISSUE TITLE
Error: loading vars file '/goss/'

### ISSUE THREAD

**Issue by fracasula** [aelsabbahy/goss#254]
Hi guys, first of all thanks for making goss :smile: 

I'm having a problem with it on Travis CI, it works locally though.

I have a `Makefile` that builds my image, it tags it and then it runs the goss tests on it.

```bash
docker_build:

	docker build \
		--build-arg BUILD_DATE=`date -u +"%Y-%m-%dT%H:%M:%SZ"` \
		--build-arg VERSION=$(CODE_VERSION) \
		--build-arg VCS_URL=`git config --get remote.origin.url` \
		--build-arg VCS_REF=$(GIT_COMMIT) \
		--build-arg CONFIG_PATH=$(CONFIG_PATH) \
		-t $(DOCKER_IMAGE):$(DOCKER_TAG) .

	docker tag $(DOCKER_IMAGE):$(DOCKER_TAG) $(DOCKER_IMAGE):dev-latest

docker_test:

	docker run --rm -it workdigitaldocker/wdjsbrowserapp npm test
	./build/goss.sh
```

The `build/goss.sh` file contains:

```bash
#!/bin/bash

export GOSS_WAIT_OPTS="-r 90s -s 1s > /dev/null"
dgoss run \
  --name dgoss.local \
  workdigitaldocker/wdjsbrowserapp:dev-latest
```

And finally the `goss.yaml` file:

```yml
command:
    curl localhost:8000:
        title: Checking main entrypoint
        exit-status: 0
        stdout:
            - "Empty body"
        stderr: []
        timeout: 1000
```

I'm on version v0.3.2 of Goss (Docker version 17.06.0-ce, build 02c1d87) and this is what I get on Travis CI:

```bash
$ ./build/goss.sh
INFO: Starting docker container
INFO: Container ID: e2c4584c
INFO: Sleeping for 0.2
INFO: Running Tests
Error: loading vars file '/goss/'
read /goss/: is a directory
INFO: Deleting container
```

Locally:

```bash
$ ./build/goss.sh 
INFO: Starting docker container
INFO: Container ID: 5496216a
INFO: Sleeping for 0.2
INFO: Running Tests
Title: Checking main entrypoint
Command: curl localhost:8000: exit-status: matches expectation: [0]
Command: curl localhost:8000: stdout: matches expectation: [Empty body]


Total Duration: 0.043s
Count: 2, Failed: 0, Skipped: 0
INFO: Deleting container
```

Any way you could think that could help me figure this out?

Thanks.

**Comment by elliotweiser** [comment]
I wonder if this is related to #248. Not sure how it can be if you're using the v0.3.2 release... 
Are you by chance grabbing the _latest_ version of the `dgoss` script?

**Comment by fracasula** [comment]
I'm doing a `curl -L https://goss.rocks/install | sudo sh` on the Travis `before_install`. I started a debug build, got in and ran a `which dgoss` and it gets installed here `/usr/local/bin/dgoss` along with the goss executable.

**Comment by elliotweiser** [comment]
I believe I found the bug...

https://github.com/aelsabbahy/goss/blob/master/extras/dgoss/dgoss#L71

**Comment by elliotweiser** [comment]
I'll submit a quick patch to fix it.

**Comment by fracasula** [comment]
That'd be great, thanks!

**Comment by elliotweiser** [comment]
@fracasula While that's☝️ waiting to be merged, you _should_ be able to get around the bug for now by doing one of two things:

1. Use the v0.3.2 release of the `dgoss` script
2. Specify `GOSS_VARS` during CI (https://github.com/aelsabbahy/goss/tree/master/extras/dgoss#goss_vars)

Best of luck!

**Comment by fracasula** [comment]
Will try soon, thanks for your help :+1:

**Comment by fracasula** [comment]
It works now. After running `curl -L https://goss.rocks/install` I replace `dgoss` with [this one](https://github.com/aelsabbahy/goss/releases/download/v0.3.2/dgoss).

It's a bit weird though. Shouldn't the setup install the 0.3.2 for both goss and dgoss?

Thanks!

**Comment by elliotweiser** [comment]
@fracasula Yes... but https://github.com/aelsabbahy/goss/blob/master/install.sh#L11

**Comment by fracasula** [comment]
Right... I guess there is a particular reason not to do `DGOSS_VER=${GOSS_VER:-$LATEST}` as well.

Thanks for your help by the way, much appreciated :+1:

**Comment by aelsabbahy** [comment]
Mostly because shell code tends to always be brittle and I didn't want to cut a new Goss release every time I make a tweak to dgoss.

Perhaps the readme should be more clear on what versions of dgoss the installer gives you.

**Comment by fracasula** [comment]
Uhm... perhaps a separate installer for dgoss could make things more clear? Also because maybe if you want goss you don't necessarily want dgoss as well I guess.

Another very useful addition would be the ability to run `dgoss -v`. Instead we get `ERROR: USAGE: dgoss [run|edit] <docker_run_params>`.

**Comment by fracasula** [comment]
@aelsabbahy didn't see your edit at first. Yes, an option for "master" but default to $LATEST would be nice indeed :+1:
