### ISSUE TITLE
FreeBSD Support

### ISSUE THREAD

**Issue by rosstimson** [aelsabbahy/goss#26]
Goss looks awesome.  It would be great to get FreeBSD support.

**Comment by aelsabbahy** [comment]
I'll gladly accept pull requests on something like this, but don't currently have the free time to undertake this task.

**Comment by jeremypruitt** [comment]
I think I'll dive into this as we need to test FreeBSD hosts and I don't want to fragment our internal toolspace to accomplish that. I don't know what I am getting into as I haven't looked at the Goss code much. How tied to Linux is this? Did you try to write in a way that other OS could be added later or has it been mostly a Linux focused effort with no real concern about future OS?

I think my first goal is just to get the command resource and reporting features to work. That might end up being all I really need.

**Comment by aelsabbahy** [comment]
How tied to Linux is this?

Goss was definitely written with only linux in mind. Ports uses /proc, package managers and services have been implemented on a per-distro basis. It's been a very long time since I used freebsd, so I'm sure there's gotchas, just not sure how many.

Did you try to write in a way that other OS could be added later or has it been mostly a Linux focused effort with no real concern about future OS?

The later.

I'm very curious on your findings once you try to get this working. I would first see if it compiles for freebsd as-is, and try a goss file with just command resource defined. Most resources are lazy loaded from the system, so it might just work for that limited use case  (if it compiles that is..).

**Comment by jeremypruitt** [comment]
I had to mess with the Makefile a bit, and I definitely don't have test coverage or anything like that, but basically the first build just worked as you suggested it might. It ran the command resource just fine, both in passing an failing conditions. This is FreeBSD 10.3-RELEASE-p11 amd64, btw. Clearly work to be done on the coverage and such, but so happy to see "it just works."

**Comment by jeremypruitt** [comment]
I just tried a number of the resources and this is what me initial efforts suggest.

Resources that can be validated on FreeBSD 10:
 - command
 - dns
 - goss
 - group
 - http
 - process
 - user

Resources that can be partially validated on FreeBSD 10:
 - file: specifically the owner and group fields don’t seem to work. The mode, size, filetype, and contains all work well.

Resources that do not validate at all on FreeBSD 10:
 - kernel-param: This makes sense as most likely tied to Linux kernel params.
 - mount?  Seems like this one should work as it uses docker/pkg/mount which has FreeBSD support. But it couldn’t find any local mounts on this FreeBSD 10 VM I am using. Needs further testing and investigation.
 - package: This makes sense as each package management system is different, even on Linux.
 - port: All the golang netstat libs seem to read /proc, including the one goss uses.
 - service: This makes sense as service management systems vary widely.

Also, as a bonus, I tried the goss “serve” command and that also worked. :)

**Comment by aelsabbahy** [comment]
Wow, that's a lot more than I expected, awesome!

* Package and service should be simple fixes, since they rely on external commands.
* Surprised about file

Wonder if mount just needs to be bumped to a newer version from docker.

**Comment by jeremypruitt** [comment]
Ya, what you say about package/service makes sense

I was surprised about the owner/group part of the file resource. I can do a little more investigation on that. The file and mount resource issues make me wonder if it is just some kind of operator error :).

Also, the Makefile has steps like lint and test that shouldn't require much (any?) change, but what about steps like all?

Lastly, the integration tests are specific to Docker, which is fantastic, but I don't think that will work for FreeBSD testing. Any thoughts on this? Modify the current test.sh? Make a new test-freebsd.sh?

**Comment by englishm-llnw** [comment]
I've [submitted](https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=220911) `sysutils/goss` as a new FreeBSD port with a caveat regarding the limited functionality linking to this issue.

[[ports]/head/sysutils/goss/pkg-message @r446527](https://svnweb.freebsd.org/ports/head/sysutils/goss/pkg-message?view=markup&pathrev=446527):

```
WARNING: goss is not yet fully functional on FreeBSD.
See https://github.com/aelsabbahy/goss/issues/26 for details.
```

**Comment by freeseacher** [comment]
are patches for freebsd is eligible ?
