### ISSUE TITLE
Unable to execute the binary file 

### ISSUE THREAD

**Issue by jeffreyyong** [aelsabbahy/goss#263]
Hi,

I follow the instructions here: https://github.com/aelsabbahy/goss#manual-installation and changed the version to v0.3.3 on my Mac. I am wondering why I can't execute the binary file at `/usr/local/bin/goss` after the download?

Regards,
Jeffrey

**Comment by aelsabbahy** [comment]
Goss doesn't run on Mac. You should be able to copy the binary to a linux box (or docker container) and execute it there.

**Comment by elliotweiser** [comment]
@jeffreyyong See [dgoss](https://github.com/aelsabbahy/goss/tree/master/extras/dgoss)

**Comment by jeffreyyong** [comment]
This is really helpful. Thanks guys :)

**Comment by aelsabbahy** [comment]
No problem, feel free to reopen if you have more questions on this.
