### ISSUE TITLE
service test for static systemd service fails

### ISSUE THREAD

**Issue by blalor** [aelsabbahy/goss#266]
When testing a systemd service that does not have an `[Install]` section and has not been (indeed, _can_not be) enabled, goss still insists that the service has been enabled (meaning it will be started automatically at system boot).

From DigitalOcean's [How To Use Systemctl to Manage Systemd Services and Units](https://www.digitalocean.com/community/tutorials/how-to-use-systemctl-to-manage-systemd-services-and-units) article:

> The state will usually be "enabled", "disabled", "static", or "masked". In this context, static means that the unit file does not contain an "install" section, which is used to enable a unit. As such, these units cannot be enabled. Usually, this means that the unit performs a one-off action or is used only as a dependency of another unit and should not be run by itself.

I have a service `influxdb-volume-manager.service` with only `[Unit]` and `[Service]` sections; it does not contain an `[Install]` section.  

```
# systemctl status influxdb-volume-manager.service
● influxdb-volume-manager.service - influxdb volume manager
   Loaded: loaded (/usr/lib/systemd/system/influxdb-volume-manager.service; static; vendor preset: disabled)
   Active: active (running) since Wed 2017-07-12 17:16:37 UTC; 22min ago
…
```

```
# systemctl is-enabled influxdb-volume-manager.service
static
```

Goss, however, thinks it's enabled, and the test fails if `enabled` is `false`.

```
# ./goss a service influxdb-volume-manager.service
Adding Service to './goss.yaml':

influxdb-volume-manager.service:
  enabled: true
  running: true
```

I believe the correct behavior here is that goss should find that the service is *not* enabled.

**Comment by aelsabbahy** [comment]
Thanks for filing this, I'll take a look at it for the next release.

**Comment by aelsabbahy** [comment]
Hmm, so looking at this further, it seems `is-enabled` returns a success status with systemctl when a service is static, for example:
```
$ systemctl is-enabled dbus.service
static
$ systemctl -q is-enabled dbus.service
$ echo $?
0
$ systemctl is-enabled cpupower.service
disabled
$ systemctl -q is-enabled cpupower.service
$ echo $?
1
```

Looking at the documentation further:
https://www.freedesktop.org/software/systemd/man/systemctl.html#is-enabled%20NAME%E2%80%A6

enabled and enabled-runtime should be the only valid "enabled" responses? Correct?

**Comment by aelsabbahy** [comment]
That said, I hesitate to make this change and I'm thinking of keeping it as-is to be consistent with:
1) The behavior of `systemctl -q is-enabled ...`
2) Other testing tools seem to be relying on the same behavior.
inspec: https://github.com/chef/inspec/blob/a6582bea9b66a9808a04c47afc88369847867035/lib/resources/service.rb#L253
testinfra:
https://github.com/philpep/testinfra/blob/25c46632ecd88ebc8757f900c3906f7b3da0f48e/testinfra/modules/service.py#L118

**Comment by aelsabbahy** [comment]
Closing this out for now, to stay consistent with other testing tools.

**Comment by blalor** [comment]
Another possible way to test the `enable`d'ness ("state" may be better) is to look at `UnitFileState` in `systemctl show <unit>`, or the state column of `systemctl list-unit-files <unit>`.  (This is much a note to future-me when I get back to using goss….)
