### ISSUE TITLE
Add the ability to run dgoss when the docker daemon is not local

### ISSUE THREAD

**Issue by rmb938** [aelsabbahy/goss#269]
I have a use case where I want to run dgoss but the docker daemon is not on the local machine and the file system is not shared. 

My idea would be to add a flag i.e ```--not-local``` or something and run ```https://goss.rocks/install``` inside the container to be tested then docker cp the goss yaml files.

**Comment by elliotweiser** [comment]
👍 

 I was playing with a similar concept outside of dgoss, but this seems like a good/valid use-case for it.

Implementation idea: only `docker cp` files instead of mounting volumes during `docker run`.  In theory this would make `dgoss` compatible against both local and remote docker daemons.

**Comment by aelsabbahy** [comment]
Docker cp would be interesting. It would slow down dgoss a little bit and not allow testing of the log content.. but those could be disclaimers. Maybe dgoss could have a cp vs mount mode that a user can toggle though env vars.

I probably won't get around to this, but if someone submits a backwards compatible PR, I would review/merge.

**Comment by elliotweiser** [comment]
I may have some to look into this next week

**Comment by rmb938** [comment]
Here is the script with the docker cp modifications I made. I didn't add a flag, just replaced everything with docker cp so it will need some work before it is ready for a pr https://gist.github.com/rmb938/bfc92e5cfffd69ba66aabb9bb0e656eb

**Comment by aelsabbahy** [comment]
Closed by #271 it's on the master branch now. I usually don't cut releases for dgoss changes, so it'll be on the github "releases" tab in the next release.
