### ISSUE TITLE
Is goss available for armv7?

### ISSUE THREAD

**Issue by sayanee** [aelsabbahy/goss#272]
I realised that goss is [available for download](https://github.com/aelsabbahy/goss/releases) for `i386` or `amd64`. 

Is there a release for `armv7` to run on boards like Beaglebone and Raspberry PI?

**Comment by aelsabbahy** [comment]
There was a request a while back for this #211.

I never followed up on it, but would review and merge a PR that added it.

**Comment by sayanee** [comment]
Tracking in #211
