### ISSUE TITLE
Spelling issue: resolveable

### ISSUE THREAD

**Issue by kgaughan** [aelsabbahy/goss#273]
A relatively minor issue, but the 'resolveable' field for dns tests is misspelled, and ought to be 'resolvable'.

I can't submit a patch at the moment, but could I suggest making 'resolvable' the default spelling and making 'resolveable' an alias of the field for backwards compatibility? If I get a chance in the next few days, I'll see if I can patch the issue myself and submit a pull request.

**Comment by aelsabbahy** [comment]
Thanks for pointing this out. Yes, this needs to be fixed.

Goss currently doesn't have support for field aliases, haven't looked at how difficult it would  be to add it. If it's complex, I don't mind a breaking change and noting it in the release notes.
