### ISSUE TITLE
Autoadd failure

### ISSUE THREAD

**Issue by adrianmkng** [aelsabbahy/goss#277]
I get an error when following the instructions from the README using 
```
> sudo goss autoadd sshd
2017/09/01 10:41:40 Can't write empty configuration file. Please check resource name(s).
```
Goss version: `0.3.4`

Is there something that I'm missing?

**Comment by aelsabbahy** [comment]
Not on a computer. But what does it say when you do a `goss a service sshd`?

As in, do you have sshd installed?

**Comment by adrianmkng** [comment]
Oops sorry. Yeh I didn't have sshd installed. Thanks!
