### ISSUE TITLE
How i can check if a command not contains a line ?

### ISSUE THREAD

**Issue by guiyomh** [aelsabbahy/goss#282]
How i can check if a command not contains a line ?

For exemple, i run `php -m` and i would like check if a module is not loaded.

i try this, but it's seem not working
```
php -m:
    exit-status: 0
    stdout:
    - apcu
    - bcmath
    - bz2
    - calendar
    - !xdebug
```

**Comment by elliotweiser** [comment]
See https://github.com/aelsabbahy/goss/blob/master/docs/manual.md#patterns for regex matching.

**Comment by aelsabbahy** [comment]
You're missing the quotes around xdebug:
```
- "!xdebug"
```

Otherwise it gets interpreted as a yaml tag.
http://www.yaml.org/spec/1.2/spec.html#id2784064

Feel free to re-open if this doesn't resolve your issue.

**Comment by elliotweiser** [comment]
@aelsabbahy Good 👀 ! I didn't catch the `!` that was already there.
