### ISSUE TITLE
http check should be able to set request headers

### ISSUE THREAD

**Issue by aelsabbahy** [aelsabbahy/goss#290]
Allow http check to adjust the request headers.

**Comment by MarkusTeufelberger** [comment]
I agree and I would actually need this functionality, though this is getting into a situation similar to #327 where request and response parameters are getting mixed up in the file format (a simple `headers` list might be interpreted as a check for headers coming from the server in the response or to set headers for the request towards the server).

**Comment by aelsabbahy** [comment]
Merged/released

**Comment by groggroggerson** [comment]
I think this was added in aa0fc088, if anybody else was curious.
