### ISSUE TITLE
validate with warnings?

### ISSUE THREAD

**Issue by nickm4062** [aelsabbahy/goss#295]
is it possible currently to do a validate and specify in the goss file to warn but not fail a test?

**Comment by aelsabbahy** [comment]
No, goss doesn't support warnings.

If you need to do something like this you can split your goss test files into a `goss.yml` and a `goss_warn.yml` then discard the exit status of the later one.

I'm personally against the idea of having warning support, but if you disagree feel free to reopen this issue with an argument for warnings.
