### ISSUE TITLE
add /etc/goss/goss.yaml or something like that for default config search path 

### ISSUE THREAD

**Issue by belonesox** [aelsabbahy/goss#302]
It will be very useful and convenient  if we can run goss ...
* briefly "goss validate" (not "goss -g /some/long/path validate", not  "GOSS_FILE=..  //")
* from different users (root+deploy user + developer + tester + ...)
* with unique and full goss file, deployed somethere in /etc/, not duplicating this file to all this users .goss, not 

Please!

Let by default, if no GOSS_FILE defined, not "-g" specified, not "~/.goss" exists,  let get "/etc/goss/goss.yaml" (or something like that) by default.

**Comment by taurus-forever** [comment]
There is a very simple and powerful workaround, just install your's 'goss' script, sample from us:

me@host:~$ cat /usr/bin/goss
#!/bin/bash
# HEADER: managed by puppet, do NOT edit manually!

/usr/bin/goss_0.3.4 -g /etc/goss/goss.yaml $@
me@host:~$ 


In this case you can have multiply goss versions "installed" on the same host (migration period to ensure new version is running well). Also you can call "goss v" only ;-)

Have fun!

**Comment by aelsabbahy** [comment]
I'd rather this be explicitly set by the user so it's clear which Goss file is being executed.
