### ISSUE TITLE
Is HTTP allowing for unix socket connection ?

### ISSUE THREAD

**Issue by ThinkBriK** [aelsabbahy/goss#303]
In an effort to test a container is running - and because our security policy forbids exposing the HTTP API endpoint - I've tried to use the HTTP checker with a socket endpoint with no success.
I really think it should be possible as I doubt being the only one stuck on this point (I'll prbably add a workaround via curl).
```
http:
  unix:///var/run/docker.sock /containers/json?filters=%7B%22name%22%3A%7B%22journalbeat%22%3Atrue%7D%7D:
    status: 200
```
Returned error  
```
Failures/Skipped:

unix:///var/run/docker.sock /containers/json?filters=%7B%22name%22%3A%7B%22journalbeat%22%3Atrue%7D%7D: status: Error: Get unix:///var/run/docker.sock%20/containers/json?filters=%7B%22name%22%3A%7B%22journalbeat%22%3Atrue%7D%7D: unsupported protocol scheme "unix"
```

**Comment by aelsabbahy** [comment]
Can you provide an example of this that I can test against. 

Also, curious what the curl workaround looks like.

**Comment by ThinkBriK** [comment]
Sure, basically I tried to test the presence of containers with docker HTTP API instead of going through the Docker client and a command resource
.
The curl workaround looks like:
```
curl -gG --unix-socket /var/run/docker.sock http:/loclahost/containers/json --data-urlencode 'filters={"name":{"MyContainer":true}}'
```

If you're looking for a container named MyContainer.

**Comment by aelsabbahy** [comment]
Closing this since there's a curl workaround.
