### ISSUE TITLE
proxy support

### ISSUE THREAD

**Issue by automaticgiant** [aelsabbahy/goss#312]
i loves me some goss. i use it as a `aws_cloudformation_stack` provisioner in terraform so that it can retry/validate with timeout before i attach a r53 route and blue/green.
but it would be even better if it had configurable proxy support (instead of no proxy support).
would like choice of:
- configure from environment
- configure in yaml

goss is targetted at in-system testing, but it's so handy and flexible with command/networkingstuff that it's great for remote checks too. but sometimes `command` with `curl` isn't enough: like https://www.claudiokuenzler.com/blog/693/curious-case-of-curl-ssl-tls-sni-http-host-header and how that doesn't work through a proxy (afaik). so if http at all, would make sense maybe to enhance with ssl+proxy becuase you might want to test if the in-system service is reachable through a given proxy.

**Comment by tzz** [comment]
Typically Go programs respect `http_proxy` and `https_proxy` but Goss doesn't seem to in my testing. Either way, I'd love this as well.

**Comment by aelsabbahy** [comment]
Goss is intended to test the local machine not the remote one. In my opinion proxy support makes sense to test local configuration.

However, taking on some of the challenges posted in that blog post are definitely out of scope for goss and should be delegated to specialized commands that goss can leverage through `command` test if needed.

**Comment by aelsabbahy** [comment]
Approved:
1. Goss should respect standard http proxy environment variables.
2. Goss http test should support `proxy:`

**Comment by aelsabbahy** [comment]
I think the was closed a while back by #589 

Let me know if I'm mistaken and I'll reopen
