### ISSUE TITLE
Expose all output formats on the same HTTP endpoint

### ISSUE THREAD

**Issue by c10l** [aelsabbahy/goss#318]
It would be good to be able to run the HTTP endpoint once and let the clients pick the output format, either via HTTP headers or a URL parameter, e.g. `http://localhost:8080/healthz?format=json`

That way you'd need to run only one endpoint and use it for machine-friendly healthchecks (JSON), human validation (rspecish), CI jobs (JUnit), etc.

**Comment by pysysops** [comment]
Interesting idea... This might not be too difficult to do.

**Comment by aelsabbahy** [comment]
Not overly complex, but caching will have to be refactored a little bit.

**Comment by aelsabbahy** [comment]
closed by #609
