### ISSUE TITLE
Detection of deb package manager is incorrect

### ISSUE THREAD

**Issue by guillemj** [aelsabbahy/goss#320]
The detection in DetectPackageManager for the deb package manager seems incorrect. There's no such command as deb, the command should be dpkg. :)

**Comment by aelsabbahy** [comment]
Good catch, guess the `DetectDistro` was working well, so no one noticed :)

Feel free to submit a pull request, otherwise I'll fix it with the next release.

**Comment by catdevman** [comment]
@aelsabbahy I am new to writing Go but I would like to fix this.  Anything special I need to know before I get started.  Looks like it would just be changing "deb" to "dpkg".  Seems like it might need a regression test but wasn't sure if you had that sort of suite. Just looking for an easy place to get my toes wet.
