### ISSUE TITLE
Sleep not working

### ISSUE THREAD

**Issue by devfelipereis** [aelsabbahy/goss#321]
Hello!

I'm trying to run my test but seens that sleep is not working.

`dgoss run -e GOSS_SLEEP=0.9 -i MYIMAGE bash`

Then:

```
INFO: Starting docker container
INFO: Container ID: c7286799
INFO: Sleeping for 0.2 <----- This should be 0.9, right?
INFO: Running Tests
...........
Failures/Skipped:

Process: supervisord: running:
Expected
    <bool>: false
to equal
    <bool>: true

Total Duration: 0.145s
Count: 32, Failed: 1, Skipped: 0
INFO: Deleting container
```
I'm new here, am I doing something wrong?

Thank you!

**Comment by aelsabbahy** [comment]
`GOSS_SLEEP=0.9 dgoss run -i MYIMAGE bash`

The `GOSS_SLEEP` is for the dgoss script (host), not the goss run (container).

I'll update the docs clarifying, if it's confusing.

**Comment by aelsabbahy** [comment]
dgoss is ~100 line shell wrapper around goss and docker.
