### ISSUE TITLE
dgoss race condition on sercvice boot

### ISSUE THREAD

**Issue by JackLeo** [aelsabbahy/goss#325]
As linked in https://github.com/aelsabbahy/goss/issues/324 and https://github.com/aelsabbahy/goss/issues/323 I am building a Docker image that would validate the automation. The goal is to use the same test suite for Docker and for real installs ad-hoc basis.

So I have my own docker image that installs and sets up RabbitMQ. The only difference there is on real system it runs through systemd and on Docker its:
```docker
CMD ["rabbitmq-server"]
```

I've noticed a difference in behaviour when running dgoss run and edit.

dgoss run
```
dgoss run rabbitmq-docker-image 
INFO: Starting docker container
INFO: Container ID: <ID>
INFO: Sleeping for 0.2
INFO: Running Tests
User: rabbitmq: exists: matches expectation: [true]
Port: tcp6:5672: listening:
Expected
    <bool>: false
to equal
    <bool>: true
Package: rabbitmq-server: installed: matches expectation: [true]
Package: rabbitmq-server: version: matches expectation: [["3.5.0n"]]
```

dgoss edit
```
dgoss edit rabbitmq-docker-image
INFO: Starting docker container
INFO: Container ID: <ID>
INFO: Run goss add/autoadd to add resources
sh-4.2# goss validate
....

Total Duration: 0.054s
Count: 4, Failed: 0, Skipped: 0
```

**Comment by JackLeo** [comment]
RTFM applies to this. Setting GOSS_SLEEP sorted it out. I guess it would be nice to apply this in a smarter way such as waiting for port listen or file appearing rather than expanding all the test runs by a set amount of time representing the worst case scenario or otherwise being flaky.

Example test for this is simple bash script:
```bash
timeout 120 bash -c 'until echo > /dev/tcp/${IP}/9042; do sleep 1; done
```
where `IP` is the IP to be monitored.

**Comment by aelsabbahy** [comment]
Take a look at goss_wait and the related options.

Here's an example:
https://github.com/aelsabbahy/dgoss-examples/tree/master/vote

Feel free to reopen if that doesn't meet your needs.

**Comment by JackLeo** [comment]
Looks exactly like what I need. I'll test it tomorrow.

**Comment by JackLeo** [comment]
So it does work, however, is there a timeout to that? If I understand, I should pass something like that through "GOSS_WAIT_OPTS", but there is no information for what it refers to or what it accepts or not that I can find.
