### ISSUE TITLE
How can i do http request body , contains string assertion

### ISSUE THREAD

**Issue by souravabhijith** [aelsabbahy/goss#326]
As of now I have written in goss.yaml file . I have a validation which checks whether if /ping is hit, I am getting "pong" or not.
http:
  http://localhost:8080/ping:
    status: 200
    timeout: 30000
    body: [pong]

My doubt is ,
1) In the above declaration, Will the response whatever I got will be matched exactly with the content inside the []. 
2) Now we are chaning the server to return not just a fixed pong response, but a very large json, which i dont want to copy paste entirely in goss.yaml. 

Is there any way I can specify body containing these specific substrings? (Any or all)

I looked into consist-of, It seems to be not working and giving an error.

**Comment by pysysops** [comment]
Hey, @souravabhijith I think that the http resource matches on an array of values (for each value, does it have a match in the body).

So something like this:
```
http:
  http://localhost:8080/health:
    status: 200
    timeout: 30000
    body:
      - '"database-connect":true'
      - '"service-api":"healthy"'
```

Would match various healthcheck results. One thing I would say is that if the app health endpoint fails it should probably return a non 200 status (usually 500) which would make the http check fail so you might not even need to check the body?

I _think_ you can pass an array of regular expressions into body as described here: https://github.com/aelsabbahy/goss/blob/master/docs/manual.md#patterns but I haven't tried it myself.

Something I recommend with YAML is using single quotes around strings. you avoid the need to escape special characters. 

Hope this helps :)

Tim.
