### ISSUE TITLE
Enable basic auth for http/https checks

### ISSUE THREAD

**Issue by Ntr0** [aelsabbahy/goss#336]
In order to check some functionality of our webservers, I need to provide credentials via basic auth in the http request. I already implemented this in https://github.com/aelsabbahy/goss/pull/327 but got no response so far. So I'm hoping for some feedback here.

**Comment by sublimino** [comment]
Thanks for your work on this @Ntr0 : ]

Issue #327 is merged, and the docs updated https://github.com/aelsabbahy/goss/blob/master/docs/manual.md#http

Can this issue be closed?

**Comment by Ntr0** [comment]
sure ;)
