### ISSUE TITLE
Verify slow starting http  - Help wanted

### ISSUE THREAD

**Issue by kaizen63** [aelsabbahy/goss#337]
Hello,
I want to verify a docker container running logstash with dgoss. Unfortunately logstash needs approx 30s to start. During this time I cannot check its port (9600). 

How can I add a delay and timeout to the http check?

**Comment by pysysops** [comment]
Hey! I think the retry timeout and sleep options are what you're looking for.

Check the output of 'goss validate --help' for details or https://github.com/aelsabbahy/goss/blob/master/docs/manual.md#validate-v---validate-the-system

Hope that helps.

**Comment by pysysops** [comment]
Hey @kaizen63 did this help you achieve what you wanted to?

**Comment by kaizen63** [comment]
Hello Tim,
yes it helped. Tx a  lot.
