### ISSUE TITLE
dgoss testing inconsistency

### ISSUE THREAD

**Issue by mgarber-ops** [aelsabbahy/goss#342]
Hello,

Firstly thanks for introducing this great tool as it appears to have great potential and I'm anticipating to integrate it with my preexisting CI/CD Pipeline. With that said, I've been banging my head on this issue for quite a bit and would appreciate any feedback you can provide:

* Below I'm writing some tests after executing my container with an Environmental Variable. In my application the instantiation of NODE_ENV will result in a configuration file being written at runtime *

$ dgoss edit -e NODE_ENV=Staging ............../composer-api:6e8b2f1
INFO: Starting docker container
INFO: Container ID: c3d689a9
INFO: Run goss add/autoadd to add resources
# goss a file /var/www/config.js
Adding File to './goss.yaml':

/var/www/config.js:
  exists: true
  mode: "0644"
  size: 1057
  owner: root
  group: root
  filetype: file
  contains: []

** As we can see here my Docker container ran successfully and dgoss was able to detect that a config.js was generated **

# exit
INFO: Copied '/goss/goss.yaml' from container to '.'
INFO: Deleting container
dgoss run -e NODE_ENV=Staging .................../composer-api:6e8b2f1
INFO: Starting docker container
INFO: Container ID: 9c31c58f
INFO: Sleeping for 0.2
INFO: Running Tests
File: /var/www/config.js: exists:
Expected
    <bool>: false
to equal
    <bool>: true
File: /var/www/config.js: mode: skipped
File: /var/www/config.js: owner: skipped
File: /var/www/config.js: group: skipped
File: /var/www/config.js: filetype: skipped
File: /var/www/config.js: size: skipped

Failures/Skipped:

File: /var/www/config.js: exists:
Expected
    <bool>: false
to equal
    <bool>: true
File: /var/www/config.js: mode: skipped
File: /var/www/config.js: owner: skipped
File: /var/www/config.js: group: skipped
File: /var/www/config.js: filetype: skipped
File: /var/www/config.js: size: skipped

Total Duration: 0.004s
Count: 6, Failed: 1, Skipped: 5
INFO: Deleting container

For whatever reason my tests are always successful when using 'dgoss edit' on my running container but when trying to execute the same tests with 'dgoss run' the tests fail. To provide context within my Docker container the last CMD command is to run a shell-script at run-time which is responsible for generating /var/www/config.js.

Let me know if any other additional information is required.

Best,

Matthew

**Comment by aelsabbahy** [comment]
Is this a race condition where goss validate is running prior to the file existing?

Try upping the `GOSS_SLEEP` or better yet defining a `goss_wait.yaml`

**Comment by aelsabbahy** [comment]
Feel free to re-open this if you do not feel GOSS_SLEEP and goss_wait.yaml resolve this.
