### ISSUE TITLE
Implement gorelease and add brew support

### ISSUE THREAD

**Issue by estahn** [aelsabbahy/goss#349]
It would be great to see goreleaser added and in the process add brew support.

https://github.com/goreleaser/goreleaser
https://goreleaser.com/#homebrew

**Comment by caarlos0** [comment]
i can help with that :)

**Comment by petemounce** [comment]
I started #380 with what's already present.

**Comment by petemounce** [comment]
Now, #405, #406.

**Comment by estahn** [comment]
@petemounce Any movement on this?

**Comment by petemounce** [comment]
Out of interest - if we made the binaries be built and added to the releases, but clearly set expectations that the macOS and Windows ones are pre-alpha and expected to fail or not support all features, then fixed them incrementally as they're reported, would that be valuable?

**Comment by caarlos0** [comment]
@petemounce sounds good to me!

**Comment by petemounce** [comment]
@caarlos0 @estahn see #585 and then I think we can come back to this, maybe?
