### ISSUE TITLE
Semver comparison hints

### ISSUE THREAD

**Issue by vromero** [aelsabbahy/goss#355]
Hi all,

Thanks for this great piece of OSS.

I was wondering if there is a recommended way to bifurcate with the gotpl based semver versions.

I'm using dgoss to test a dockerimage with multiple versionso of the contained software and some tests apply to versions prior to X, and other to verions after Y or both.

I can probably do it with some simple regexes but I was hoping there was something better integrated.

**Comment by aelsabbahy** [comment]
Currently, regex is the only solution. I want to add semver support, but it's hard to find a standard that works across all package managers.

If you have some library (preferably Go) or OSS software that you feel handle this problem in a generic cross platform way let me know and I'll dig into it.

**Comment by vromero** [comment]
I see, thanks for the quick response.

**Comment by aelsabbahy** [comment]
Adding support for this library could be neat: https://github.com/blang/semver#ranges 

It wouldn't work for all package managers, but would work with anything compliant with the semver spec.

**Comment by vromero** [comment]
Agree, if it is not semver then whoever did choose that version scheme didn't mean it to be comparable.

**Comment by pedroMMM** [comment]
@aelsabbahy I was playing with this on my repo and I had success by using https://github.com/hashicorp/go-version and creating another set of advanced mather. What I have already kind of works for me (it needs a better messaging). Would you like me to clean it up and create a PR?

**Comment by aelsabbahy** [comment]
I would be interested in a semver matcher. I would prefer it be created as a gomega custom matcher that uses go-version.

**Comment by pedroMMM** [comment]
@aelsabbahy This can be closed now. Also I will not mention the issue on commits anymore, that got messy fast :(

**Comment by aelsabbahy** [comment]
Yeah works better in pr message.

Also, you don't have to rebase/push if there are no conflicts most of the time. Sometimes test count gets out of wack.
