### ISSUE TITLE
Remove dependency on cgo

### ISSUE THREAD

**Issue by ryancox** [aelsabbahy/goss#36]
Use of cgo complicates the build process, introduces more build-time dependencies and makes porting more difficult. Further, when using goss on systems like Alpine ( which use musl ), it requires adding glibc for goss to be able to run. This reduces the applicability of goss, since users may not want to add additional container / OS dependencies just to run tests.

It appears that adding --ldflags '-extldflags "-static"' to the build call would be one way to work around this. However, refactoring the util/group code to that looks like it was forked from the standard library seems like a cleaner way forward.

**Comment by aelsabbahy** [comment]
@ryancox I'm guessing golang's user implementation would also cause issues:

https://github.com/golang/go/blob/master/src/os/user/lookup_unix.go

**Comment by andlabs** [comment]
All the functions used by that file are specified in POSIX. If musl is not POSIX compliant, that's a bug in musl...

**Comment by andlabs** [comment]
Ah, this is fixed in Go 1.6. https://github.com/golang/go/issues/11319

**Comment by aelsabbahy** [comment]
Awesome, thanks a bunch for your help @andlabs

**Comment by ryancox** [comment]
@andlabs This isn't a compile time / posix compliance issue. This root cause is that with cgo an external linker is used that does not yield a fully static binary by default ( ldd shows you .so files ). See: http://blog.hashbangbash.com/2014/04/linking-golang-statically/

**Comment by ryancox** [comment]
Coding up a replacement using the os/exec package in conjunction with a 'getent group <name | id>' call might be an option. This would remove the cgo code and maintain all current functionality. Less efficient, but for this use case would provide perfectly acceptable performance. It would also get ride of the forked code from the stdlib.

**Comment by aelsabbahy** [comment]
Hmm.. some thoughs:
* os/exec might not be a bad idea, but leaving that as last resort
* Noticed hashicorp https://github.com/hashicorp/nomad/issues/505 went back and forth on this, wonder  how other projects approached this issue

Some experimentation, tried the following, it compiled a binary, but the binary segfaults when executed:
`docker run -e GO15VENDOREXPERIMENT=1 --rm -v $GOPATH:/go -w /go/src/github.com/aelsabbahy/goss golang:1.6-alpine sh -c 'apk update && apk add gcc musl-dev && go build -a github.com/aelsabbahy/goss/cmd/goss'`

**Comment by ryancox** [comment]
I was poking around in the Docker source to see how they solve this problem. It depends on https://github.com/opencontainers/runc/tree/master/libcontainer/user  ... Which solves this problem by parsing /etc/passwd and /etc/group by hand.

This seems clean, but it occurs to me that this doesn't work if you are using LDAP. Then I found a different PR: https://github.com/docker/docker/pull/1096 which talks about this specifically ( and has the stated objective of dropping cgo dependency ). They basically don't support LDAP/NIS.

I noticed that https://github.com/mitchellh/go-homedir/blob/master/homedir.go handles a similar problem by using os/exec.

**Comment by aelsabbahy** [comment]
I'm okay with dropping LDAP support for cross functionality. Don't think LDAP user details is really something goss should be responsible testing anyways.

Need to first make sure that if I drop the user/group code the binary runs properly on alpine. Haven't dug into if any of the external dependencies use cgo.

**Comment by ryancox** [comment]
A good test is to run 'ldd' on the goss executable after building it. It should look like this:
```
$ ldd goss
     not a dynamic executable```

**Comment by aelsabbahy** [comment]
Did a quick test commenting out all the os/user and group code and compiled with CGO_ENABLED=0 and it works!

Basically need to migrate to the runc user/group implementation to fix this.

**Comment by aelsabbahy** [comment]
Fixed in [v0.0.22](https://github.com/aelsabbahy/goss/releases/tag/v0.0.22)

Let me know if you have any issues.
