### ISSUE TITLE
Package checks failing but packages are installed

### ISSUE THREAD

**Issue by NeilJ247** [aelsabbahy/goss#360]
Hi,

I am having a few package checks that are failing even though I can see they are installed. For example:

```Package: vim: installed:
Expected
    <bool>: false
to equal
    <bool>: true

Package: nc: installed:
Expected
    <bool>: false
to equal
    <bool>: true

Package: php70u-mysql: installed:
Expected
    <bool>: false
to equal
    <bool>: true

Package: mysql: installed:
Expected
    <bool>: false
to equal
    <bool>: true

Package: python-pip: installed:
Expected
    <bool>: false
to equal
    <bool>: true
```
If I run the container and check manually I can see they are there:

```docker run --entrypoint "/bin/sh" myimage -c "whereis vim nc mysql pip"
vim: /usr/bin/vim /usr/share/vim
nc: /usr/bin/nc
mysql: /usr/bin/mysql /usr/lib64/mysql
pip: /usr/bin/pip2.7 /usr/bin/pip


docker run --entrypoint "/bin/sh" myimage -c "php -m | grep mysql"
mysqli
mysqlnd
pdo_mysql
```

The docker image is using Centos 7 and using Yum to install the packages.

Maybe I am missing something or checking these incorrectly?

Thanks.

**Comment by fsantiag** [comment]
@NeilJ247 Have you solved this issue? I am facing the same problem, would like to hear your thoughts. ;)

**Comment by NeilJ247** [comment]
@fsantiag Unfortunately not :(

**Comment by keithy** [comment]
Same issue on fedora atomic host, which uses rpm-ostree

**Comment by aelsabbahy** [comment]
rpm-ostree isn't a package manager that Goss supports currently.

@NeilJ247 and @fsantiag I'm not able to reproduce this issue. Can you provide a set of steps to reproduce this.

Perhaps a docker image showcasing a package that fails to be correctly recognized?
