### ISSUE TITLE
Is it possible to validate http requests with a request body?

### ISSUE THREAD

**Issue by AhmadAbdelghany** [aelsabbahy/goss#361]
In my goss.yaml, I have validating that nginx server is serving the 'endpoint':
```
http:
  http://0.0.0.0:80/endpoint:
    status: 200
```
As expected, it generates:
`HTTP: http://0.0.0.0:80/endpoint: status: matches expectation: [200]
`

Is there a way to test that nginx is enforcing max request body limits by returning "413 Entity Too Large" when request body exceeds the limit? In other words, is it possible to verify something like:
```
http:
  http://0.0.0.0:80/endpoint -d {{readFile "body-too-large.json"}}:
    status: 413
```

**Comment by aelsabbahy** [comment]
Consolidating chat to this ticket: https://github.com/aelsabbahy/goss/issues/484
