### ISSUE TITLE
RHEL 6.x - failed to check upstart service

### ISSUE THREAD

**Issue by jaymecd** [aelsabbahy/goss#364]
Installed `amazon-ssm-agent` package on RHEL-6.5, which is controls service by `upstart` with instruction file `/etc/init/amazon-ssm-agent.conf`.

Following config failed:

```
service:
  amazon-ssm-agent:
    enabled: true
    running: true

---

Fail 1 - Service: amazon-ssm-agent: enabled: doesn't match, expect: [true] found: [false]
Fail 2 - Service: amazon-ssm-agent: running: doesn't match, expect: [true] found: [false]
```

While `upstart` reports:

```
$ initctl status amazon-ssm-agent; echo $?
amazon-ssm-agent start/running, process 5793
0
```

After deep dive, figured out that [service_upstart.go#L34](https://github.com/aelsabbahy/goss/blob/291b44151057d373db7523797e8d6bd5c7488ce0/system/service_upstart.go#L34) has fallback to `service_init`, but not vice versa.
Service detected as `init` and ignores `upstart` definition.

Therefore, suggest to have `FallbackService` service to be used in [system.go#L97](https://github.com/aelsabbahy/goss/blob/165fc70189ee67b6065651e4af5f44f0c355193e/system/system.go#L97):

```
	switch DetectService() {
        . . . . . . . 
	case "upstart":
		sys.NewService = FallbackService(NewServiceUpstart, NewServiceInit)
	default:
		sys.NewService = FallbackService(NewServiceInit, NewServiceUpstart)
	}
```

That would also require to remove direct fallback from `service_upstart`.

Or it could be `ChainedServices(services ...func(string, *System, util2.Config) Service)` function.
That would allow to define flexible fallback chain.

@aelsabbahy wdyt?

**Comment by aelsabbahy** [comment]
Had no idea rhel used upstart for anything.

Wonder if goss would benefit from a default (or default chain) + a `driver` attribute that allows overwriting which driver to use. So someone can use rhel and set Deb as a PKG manager for example.

I assume upstart on rhel is fairly rare.

Or alternatively, define a chain and say the priority is:
* Systemd
* Upstart
* Init

**Comment by jaymecd** [comment]
Thanks to AWS, it uses :)

This `driver` attribute relates to `package`, not `service` declaration. Am I right?
My only intent was, if upstart has fallback to sysv, then sysv should have a fallback to upstart.
And that would be easily achieved with wrapper service explained above.

**Comment by aelsabbahy** [comment]
Sorry, what I meant by the driver concept is for it to be a general flag to override the detected type, it would apply to package and service.

The chain solution might be the simplest IF it doesn't lead to weird error messages or confusion.

I think in my mind upstart on rhel feels as awkward/rare as Deb on rhel :)

**Comment by aelsabbahy** [comment]
In the meantime the workaround would be to use `command` test to run the upstart test.

**Comment by jaymecd** [comment]
right. that's what I've did sofar.

**Comment by aelsabbahy** [comment]
Consolidating discussion to this ticket https://github.com/aelsabbahy/goss/issues/539
