### ISSUE TITLE
feature request: specify testfile

### ISSUE THREAD

**Issue by gtmtech** [aelsabbahy/goss#369]
It would be great if goss could specify a testfile- in my usage, I have many different flavours to choose from, I dont want to have to manage renaming the testfile I want to select as goss.yaml, it would be great if I could just do `goss validate < some-file` or `goss validate --testfile foo.yaml`

Thanks for the great tool btw 👍

**Comment by geku** [comment]
You can already do this with option `-g`: https://github.com/aelsabbahy/goss/blob/master/docs/manual.md#-g-gossfile
