### ISSUE TITLE
junit output broken in v0.3.6

### ISSUE THREAD

**Issue by aelindeman** [aelsabbahy/goss#376]
The most recent version includes a change from #304, which prints the Docker logs if the container failed to start, and prints `docker top` if the container ran successfully, both to stdout. This breaks the intent of #291, which was to redirect all non-test-result output to stderr, as to not break parsing junit results with an XML parser.

Before making a pull request I'd like to suggest doing one of two things, to gauge which option sounds better:

- redirecting `docker top` and `docker logs` commands to stderr (easy quick fix)
- adding an `output-file` parameter to the `junit` formatter, using a formatter option like the nagios formatter (slower more "correct"-seeming fix)

**Comment by aelsabbahy** [comment]
Merged/released. Fixed in #473
