### ISSUE TITLE
Adding non-A dns records does not work

### ISSUE THREAD

**Issue by kasimon** [aelsabbahy/goss#377]
According to the manual, the following should work:
<pre>
dns:
  # Validate a PTR record
  PTR:8.8.8.8:
    resolvable: true
    server: 8.8.8.8
    addrs:
    - "google-public-dns-a.google.com."
</pre>

This does not work for me:
<pre>
$ goss -v
goss version v0.3.6
$ goss add dns PTR:8.8.8.8
Adding DNS to './goss.yaml':

PTR:8.8.8.8:
  resolvable: true
  addrs:
  - 8.8.8.8
  timeout: 500
</pre>

In fact any dns record type is ignored and always an A record is requested. Examples:

<pre>
$ dig +short -t MX google.com
30 alt2.aspmx.l.google.com.
40 alt3.aspmx.l.google.com.
50 alt4.aspmx.l.google.com.
10 aspmx.l.google.com.
20 alt1.aspmx.l.google.com.
$ goss a dns MX:google.com
Adding DNS to './goss.yaml':

MX:google.com:
  resolvable: true
  addrs:
  - 172.217.17.142
  - 2a00:1450:400e:802::200e
  timeout: 500
</pre>

**Comment by gsauthof** [comment]
Note that the example from the manual explicitly sets the `server:` key while your examples don't.

When I copy the PTR example from the manual as-is, it works for me as expected with goss 0.3.6.

On the contrary, when I comment out the `server:` key such that the DNS server of my AVM FRITZ!Box is used, the `goss validate` fails with:

    DNS: PTR:8.8.8.8: addrs:
    Expected
        <[]string | len:1, cap:1>: ["8.8.8.8"]
    to contain element matching
        <string>: dns.google.

It does also work when I directly specify my provider's DNS server  (which the FRITZ!Box resolves too, as well).

When I test with `dig @8.8.8.8 -x 8.8.8.8` etc. I don't see any differences in the answers between the different DNS servers.

Thus, it looks like the Goss DNS code is incompatible to some DNS server implementations.

**Comment by aelsabbahy** [comment]
You have to explicitly set the sever attribute to test a PTR record.

"With the server attribute set, it is possible to validate the following types of DNS record:..."

Try setting the server attribute to your DNS server and let me know if that doesn't work.

**Comment by gsauthof** [comment]
Oh, I over-read this part - yes, when I explicitly set the `server:` to the address of my FRITZ!Box, it works as well.

FWIW, a `dig -x 8.8.8.8` works without specifying the DNS server explicitly. Thus, this limitation is a bit unexpected.

Btw, testing the PTR of an IPv6 address isn't supported yet, right?

https://github.com/aelsabbahy/goss/blob/master/system/dns.go#L39-L40

looks like colons in an IP address aren't expected.

Should I open a new issue for this?

**Comment by aelsabbahy** [comment]
Glad the DNS test is working for you.

Yes, for ipv6 if you still need it, please open a new issue.
