### ISSUE TITLE
Add ToUpper and ToLower support for Template Pipelines

### ISSUE THREAD

**Issue by mattrice** [aelsabbahy/goss#383]
I have a series of URLs in my Docker image that I want to test and I already have separate tests written for mixed-case URLs. It would be nice to allow Template pipelines to change the case of a Template string to force (e.g.) lowercase URL testing to try to maintain separation of concerns while not forcing the caller to lowercase the URLs to test.

For example:

```
http:
  # mixed-case URL tests
  # <snip>

  # URL tests from --vars
  {{range .Vars.urls}}
    http://localhost/{{. | ToLower}}
  {{end}}
```

Currently, that syntax gives an error:

```
2018/09/05 12:33:07 template: test:34: function "ToLower" not defined
```

**Comment by jaymecd** [comment]
this one should be closed as referenced PR was merged :)

**Comment by aelsabbahy** [comment]
Yup, thanks for catching this.
