### ISSUE TITLE
Testing of remote machines?

### ISSUE THREAD

**Issue by skyzyx** [aelsabbahy/goss#388]
**Use-case:** I maintain a customized Amazon EC2 AMI for my company, wherein I use [Packer](https://www.packer.io) and [Ansible](https://docs.ansible.com/ansible/latest/) to build the AMI, then spin-up a new EC2 instance with it, and run tests against it from my Mac. I'm currently using [Testinfra](https://testinfra.readthedocs.io/en/latest/) and [pytest](https://docs.pytest.org/en/latest/) (Python) to run the tests over SSH against the EC2 instance.

The performance leaves a lot to be desired, even after working to optimize the socket re-use in Python-land. I've been writing a lot of Golang lately, and have been impressed by the performance, leading me to look at alternatives to Testinfra written in Golang.

Are there any plans to enable Goss to execute tests over SSH against a remote Linux-based machine?

**Comment by macklus** [comment]
+1

i came here searching for framework who allow me to test Amazon AWS infraestructure. 
Use of remote tests should be an important feature

**Comment by oldsj** [comment]
We are using https://github.com/YaleUniversity/packer-provisioner-goss to use goss as a packer provisioner so it will run goss tests as a part of the packer build, and if the goss tests fail, the AMI fails as well.

**Comment by berney** [comment]
Currently you most checks can only be run locally. You upload/install and run goss on the remote system in `serve` mode and use it as a healthcheck. You can test some things like `tcp` and `http` to test that a remote server has some expected behaviours.

In addition to packer-provisioner-goss taht oldsj pointed out, The goss README also links to an Ansible module `degoss` that can be used to install goss, run tests, and then uninstall it. You'd have to test it to see if its faster than your Testinfra pytest setup.

I'm curious to know how any of your experiments compare - speed, flexibility, ease-of-use etc.

**Comment by petemounce** [comment]
I'm using both https://github.com/YaleUniversity/packer-provisioner-goss (to force tests to run before image-capture) and https://github.com/indusbox/goss-ansible (to iterate). Both work well.

**Comment by aelsabbahy** [comment]
Goss only does local validation, see: #6 and #208

Summary: Goss can't work remotely because it doesn't rely on external commands for a lot of it's tests.

**Comment by q2dg** [comment]
Maybe https://github.com/teuton-software/teuton can help
