### ISSUE TITLE
http check: url not working

### ISSUE THREAD

**Issue by KEZHwMlXV1vFzs6QvY8v5WjX5** [aelsabbahy/goss#393]
this does not show the same result

```
   https://puppetserver:8140/puppet-ca/v1/certificate/ca?environment=rolling:
    status: 200
    allow-insecure: true
```
`not ok 10 - HTTP: https://puppetserver:8140/puppet-ca/v1/certificate/ca?environment=rolling: status: doesn't match, expect: [200] found: [400]`

so **that way I get a 400**. Hm.

but a `curl https://puppetserver:8140/puppet-ca/v1/certificate/ca?environment=rolling` **result: 200**

is that a quoting issue?

**Comment by berney** [comment]
Probably there is a difference between how Goss is connecting and curl is connecting. Either connect via a proxy, or sniff, use some debugging etc to view the exact request that Goss send and compare that to what curl sent. Probably a missing header(s), or differences in header(s) are causing the server to respond with HTTP 400.

**Comment by KEZHwMlXV1vFzs6QvY8v5WjX5** [comment]
it might have sth to do with the http method used to request the url but we skipped those tests so. Id just close this

**Comment by bwaters** [comment]
I narrowed this down to an issue with the query parameters.  Urls that do not have query parameters work correctly but there is something mallformed with the parameters.  i reproduced this on 3.8

**Comment by berney** [comment]
Can you observe the HTTP request from goss and from `curl`, and observe the difference? You might be able to observe via the HTTP server logs, or from sniffing (e.g. wireshark), or by using a proxy in the middle (e.g. burp).
