### ISSUE TITLE
Is there an icon or logo ?

### ISSUE THREAD

**Issue by rgarrigue** [aelsabbahy/goss#397]
Hello

Is there a Goss logo / icon somewhere ? That's just a little thing I do for more convivial work, putting logo's as project image in our Gitlab

Keep on the good work on Goss !
Best regards,

**Comment by Midacts** [comment]
It would be great to see an icon for the project.   : )

**Comment by aelsabbahy** [comment]
An icon would be nice.. I'm severly artistically challenged.

Any idea on where to get started with something like this?

**Comment by midacts** [comment]
It looks like rgarrigue would make one?
He is a convivial logo maker extraordinaire?

**Comment by rgarrigue** [comment]
Here to you, my best graphical skill

-----
| G |
-----

(sorry, wrong pick, I'm a CLI guy mostly)
