### ISSUE TITLE
Not enough arguments in call to mounts.GetMounts

### ISSUE THREAD

**Issue by SpokeyWheeler** [aelsabbahy/goss#402]
Apologies if I'm misunderstanding something. I'm trying to build goss on my Mac using "go get" and I get this error.

github.com/aelsabbahy/goss/system/mount.go:91:33: not enough arguments in call to mount.GetMounts
	have ()
	want (mount.FilterFunc)

According to this, https://github.com/moby/moby/blob/master/pkg/mount/mount.go#L51 if there are not any arguments you should pass in nil.

**Comment by petemounce** [comment]
You might be interested to watch #405.

**Comment by SimonBaeumer** [comment]
The pull-request #410 should fix your problem. Could you check it?

**Comment by rnrbarbosa** [comment]
#410 not working either, same error

**Comment by SimonBaeumer** [comment]
Did you updated the dependencies by using `dep ensure` or `make deps`?
Is `goss` installed in your `GOPATH` under `github.com/aelsabbahy/goss`?

**Comment by rnrbarbosa** [comment]
replaced glide with dep and copied the Gopkg.toml from @SimonBaeumer (https://github.com/aelsabbahy/goss/pull/410/files#diff-836546cc53507f6b2d581088903b1785) and it worked fine for me after "dep insure"

**Comment by SimonBaeumer** [comment]
That's very good!
But why did you need to copy the `Gopkg.toml`, I thought you checked out my branch :D

**Comment by rnrbarbosa** [comment]
I did it in the end and it works flawless. At the beginning I was not familiar with dep...when I got it, I understood better your PR, which is perfect fix.
