### ISSUE TITLE
Resource fpm

### ISSUE THREAD

**Issue by estahn** [aelsabbahy/goss#408]
@aelsabbahy I would like to check the status of `php-fpm`, e.g. queue length. Would you accept a pull request for an fpm resource?

**Comment by aelsabbahy** [comment]
Sorry for the delay in answering this.

I've created a https://github.com/aelsabbahy/goss/blob/master/.github/CONTRIBUTING.md#feature-requests detailing the scope of goss.

In my opinion php-fpm is a highly specific usecases and not a general OS check that goes should support natively.

You can always use the `command` resource to test this if needed.

Feel free to reopen the ticket if you disagree or feel I've misunderstood php-fpm.
