### ISSUE TITLE
Regex flavour

### ISSUE THREAD

**Issue by timstoop** [aelsabbahy/goss#41]
Hi,

You might want to point out in the docs that you're using the POSIX flavour regex for checking the contents of files. I was wrestling with my \b's and \w's before finding out I was using the incorrect flavour!

-- 
Kind regards,
Tim

**Comment by aelsabbahy** [comment]
goss uses golang's regex engine documented here: https://golang.org/pkg/regexp/syntax/

Sorry for the inconvenience, I'll update the docs with a link to that.

**Comment by aelsabbahy** [comment]
If it's not too much trouble can you paste the regex and string you were trying to match here?

**Comment by timstoop** [comment]
Well, I was actually trying to match '\b/tmp\b' to see if there's a separate partition defined in /etc/fstab. According to the docs, \b is valid, but it doesn't work:

```
:~$ cat testtab 
/some/partition/point   /tmp    tmpfs   acl,relatime,nodev,nosuid,noexec        0       2
:~$ cat issue41.yaml 
file:
  /home/tim/testtab:
    exists: true
    filetype: file
    contains:
      - /\b\/tmp\b/
      - /[[:space:]]\/tmp[[:space:]]/
:~$ goss -g issue41.yaml validate
..F

Failures:
File: /home/tim/testtab: contains: patterns not found: [/\b\/tmp\b/]

Total Duration: 0.007s
Count: 3, Failed: 1
```

**Comment by aelsabbahy** [comment]
Hmm, this is actually a bug in goss. Reopening.

**Comment by timstoop** [comment]
Hm, it works when I use this regex: /\/tmp\b/

Just not when I have a \b in front of it as well.

**Comment by aelsabbahy** [comment]
well `\b/tmp\b` in front is invalid since `space and slash are both non-word characters, so there's no "boundary"

That said, `\s/tmp\b` should work, but doesn't.. That's where the bug is.
