### ISSUE TITLE
DGoss: Healthcheck affects junit output

### ISSUE THREAD

**Issue by VibroAxe** [aelsabbahy/goss#412]
When setting the format to junit (or anything else) the docker top/docker logs output is sent to stdout

https://github.com/aelsabbahy/goss/blob/master/extras/dgoss/dgoss#L93

This means using a standard redirection > creates a file with invalid data at the top of it.

Is it possible to have the docker top/info report to the error/info channel as per the rest of the dgoss output

**Comment by aelsabbahy** [comment]
Closed/released.

**Comment by VibroAxe** [comment]
Thanks!
