### ISSUE TITLE
Can I use Goss to validate an openshift deployment?

### ISSUE THREAD

**Issue by manuq21** [aelsabbahy/goss#422]
I'm looking to validate and compare all the features added on a yaml file, with the features and configurations the deployment has after completed, to make sure all was applied as expected. Is that possible with Goss?

thanks

**Comment by thatsk** [comment]
i don't think so.

**Comment by joshgav** [comment]
@manuq21 check out kgoss in #465, I'm in fact using it within an OpenShift environment. Would love feedback, thanks!

**Comment by aelsabbahy** [comment]
@manuq21 #465 has been merged and showcases one way this can be done.

How, where, and when you run goss is up to you. Goss runs on the OS level and doesn't care if your OS is running in a container, virtual machine, cloud or k8s.

Feel free to open a new issue if you have a more specific question.
