### ISSUE TITLE
Checking the the DNS PTR of a IPv6 address

### ISSUE THREAD

**Issue by gsauthof** [aelsabbahy/goss#428]
Goss supports the checking of a reverse-DNS record of a IPv4 address fine.

But it fails for a IPv6 address like this (using goss 0.3.6):

    dns:
      PTR:2001:4860:4860::8888:
        resolvable: true
        server: 8.8.8.8
        addrs:
        - "google-public-dns-a.google.com."

It looks like the key parser doesn't expect IP addresses with colons:

https://github.com/aelsabbahy/goss/blob/2506b9448a4ec97f92c2c8556efdd52741658899/system/dns.go#L38-L41

Perhaps there also also code parts that need to be changed.

**Comment by aelsabbahy** [comment]
I think I have a fix for this. However, the dnstest.io records I was using seem to be down. Do you know a good public set of DNS records I can add as a CI test for goss?

I need records to replace the following tests + adding a test for the PTR reverse lookup scenario:
https://github.com/aelsabbahy/goss/blob/ad19527be8bc93bcee84a17ee686c4f5745aee85/integration-tests/goss/goss-shared.yaml#L71-L139

**Comment by gsauthof** [comment]
In my experience, the Google public DNS servers heavily filter DNS records. Thus, they are quite unreliable for such tests and e.g. DNSBL queries.

More reliable are the Quad9 and OpenDNS servers, e.g.:

    $ dig +short @9.9.9.9 dnstest.io caa
    0 issuewild ";"
    0 issue "comodoca.com"
    0 issue "letsencrypt.org"
    $ dig +short @208.67.222.222 dnstest.io caa
    0 issue "comodoca.com"
    0 issue "letsencrypt.org"
    0 issuewild ";"

For the reverse-PTR scenario I would use a well known address - e.g. the address of a public DNS server (cf. my original report).

    $ dig +short @208.67.222.222  -x 2001:4860:4860::8888
    google-public-dns-a.google.com.
    $ dig +short @9.9.9.9  -x 2001:4860:4860::8888
    google-public-dns-a.google.com.

**Comment by pysysops** [comment]
Will take a look at the dnstest.io records / DNS servers. They were "just working:TM:", haven't been on them for s while.
