### ISSUE TITLE
Check for gofmt compliance as part of CI

### ISSUE THREAD

**Issue by aelsabbahy** [aelsabbahy/goss#445]

**Comment by pedroMMM** [comment]
@aelsabbahy It can be closed now.

**Comment by aelsabbahy** [comment]
Thanks for catching this and thanks for all your contributions. A release is being cut as we speak with some of your changes.

By the way in the future you can add fixes #tickernumber and it'll automatically close it: https://help.github.com/en/github/managing-your-work-on-github/closing-issues-using-keywords

I'll update the PR template to include a section for this.
