### ISSUE TITLE
goss v0.3.7 'filetype: socket' regression 

### ISSUE THREAD

**Issue by taurus-forever** [aelsabbahy/goss#446]
Hi,

goss v0.3.7 has regression comparing to v0.3.6 for 'filetype: socket'.
The file type is now reported as 'file'. Sample:

```
me@server:/tmp$ sudo /usr/bin/goss_0.3.6 -g /tmp/test.yaml v
......

Total Duration: 0.000s
Count: 6, Failed: 0, Skipped: 0



me@server:/tmp$ sudo /usr/bin/goss_0.3.7 -g /tmp/test.yaml v
....F.

Failures/Skipped:

File: /var/lib/sss/pipes/pam: filetype:
Expected
    <string>: file
to equal
    <string>: socket

Total Duration: 0.000s
Count: 6, Failed: 1, Skipped: 0



me@server:/tmp$ cat /tmp/test.yaml
file:
  /var/lib/sss/pipes/pam:
    exists: true
    mode: "0666"
    size: 0
    owner: root
    group: root
    filetype: socket



me@server:/tmp$ file /var/lib/sss/pipes/pam
/var/lib/sss/pipes/pam: socket
```

**Comment by aelsabbahy** [comment]
I'm having a hard time reproducing this, can you provide me with a set of commands to get this behavior.

```
$ python -c "import socket as s; sock = s.socket(s.AF_UNIX); sock.bind('somesocket')"

$ ~/Downloads/goss a file ./somesocket
Adding File to './goss.yaml':

/home/aelsabbahy/sandbox/golang/src/github.com/aelsabbahy/goss/somesocket:
  exists: true
  mode: "0775"
  size: 0
  owner: aelsabbahy
  group: aelsabbahy
  filetype: socket
  contains: []

$ ~/Downloads/goss v
......

Total Duration: 0.001s
Count: 6, Failed: 0, Skipped: 0
```

I don't see any changes to `system/file.go` or `resource/file.go` from 0.3.6 to 0.3.7. However, goss went from Go 1.9 to 1.11.X, which may have impacted things.

**Comment by taurus-forever** [comment]
Thank you for the very fast reply here. I appreciate it!
I am absolutely confused now, I can't reproduce it any longer.

Even on the same server with old test data it works well.
I can't explain this. I have repeated the test above in a loop 1000 times, no luck.
At the morning it was reproducible with 100% cases and at least was noticed 5 times.

You can resolve the bugreport here, I will keep an eye and reopen if find a way to reproduce it.
Excuse me for the noise.

**Comment by aelsabbahy** [comment]
All good, stuff like this happens to me far too often.
