### ISSUE TITLE
dgoss can't test Os Base images

### ISSUE THREAD

**Issue by Gcozier** [aelsabbahy/goss#452]
Hello, 

I encountered an issue when I would like to perform dgoss  OS base image. In this case, it's on a Debian slim image. 

please find the goss.yaml
``` yaml
---


process:
  tini:
    running:

user:
  docker4sg:
    exists: true
    uid: 11111
    gid: 11111
    groups:
    - docker4sg
    home: /home/docker4sg

file:
  /usr/bin/tini:
    exists: true
  /etc/docker4sg_release:
    exists: true
    contains: ["hardening.sh","executed"]
```
Please find the output of it : 

```

osdebian]$ export GOSS_FILES_STRATEGY=cp
osdebian]$ dgoss run debian-goss:latest
INFO: Creating docker container
INFO: Copy goss files into container
INFO: Starting docker container
INFO: Container ID: ab1afc61
INFO: Sleeping for 0.2
INFO: Container health
Error response from daemon: Container ab1afc61158a8541314528628dce434b3ecfa8ccb19f0564d42cff62c552ad69 is not running
INFO: Running Tests
Error response from daemon: Container ab1afc61158a8541314528628dce434b3ecfa8ccb19f0564d42cff62c552ad69 is not running
```
FYI it's working fine with middleware containers.

OS: Redhat 7.5 Maipo
Docker Version: 17.06.2-ee-19 

Regards,

**Comment by aelsabbahy** [comment]
`dgoss` is just a small wrapper shell script. Can you run it with `bash -x` and see how the container is being started, it doesn't seem like the docker daemon likes it, or perhaps the sleep time is too aggressive.

**Comment by Gcozier** [comment]
Hello, 

I found how to fix that , when I modified a bit the Wrapper.

Could I propose a pull request to adapt to this case ?

Regards, 

AY
