### ISSUE TITLE
Using "Expected" for observed value in error message might be confusing to some

### ISSUE THREAD

**Issue by deftdawg** [aelsabbahy/goss#453]
This is nit picky, so feel free to ignore it.

When I'm tired my brain reads the following error message:
```
Process: goss-test: running:
Expected
    <bool>: false
to equal
    <bool>: true
```
as the expected value was false but didn't equal true.   In goss it's meant to mean the opposite, that it "expected false [observed] to equal the value true [coded check]". 

The reason my brain reads it this way is when filing bug reports its more common to use expected/actual or expected/observed.

**Comment by berney** [comment]
I also find it confusing, maybe some slight re-wording could make it clearer. Like:

```
Process: goss-test: running:
Observed
    <bool>: false
expected to equal
    <bool>: true
```

**Comment by aelsabbahy** [comment]
Goss uses gomega for matchers, which is where the verbiage comes from.

Here's the issue tracking this same request on gomega's side.

https://github.com/onsi/gomega/issues/261

**Comment by aelsabbahy** [comment]
Feel free to reopen if you feel there's something I'm missing that can be done on the Goss side of things.
