### ISSUE TITLE
wrong version installation 

### ISSUE THREAD

**Issue by pi-unnerup** [aelsabbahy/goss#458]
curl -fsSL https://goss.rocks/install | sh
and 
curl -fsSL https://goss.rocks/install | GOSS_VER=v0.3.7 GOSS_DST=~/bin sh

installs v0.3.6, would expect v0.3.7

**Comment by PlusMinus0** [comment]
Can’t confirm, 

`curl -fsSL https://goss.rocks/install | sh`
installs 0.3.6 and
`curl -fsSL https://goss.rocks/install | GOSS_VER=v0.3.7 sh`
installs 0.3.7
