### ISSUE TITLE
Integration into Docker Hub builds

### ISSUE THREAD

**Issue by CCFenner** [aelsabbahy/goss#462]
Is there a ways to use goss/dgoss in [automated repository tests](https://docs.docker.com/docker-hub/builds/automated-testing/) on Docker Hub builds?

**Comment by aelsabbahy** [comment]
I don't personally know the answer to this. Some info that might help:

* Goss generally runs on the system under test.

* Dgoss is a ~100 line shell script that essentially uses the `docker` command to start a container, copy/mount Goss binary/test yamls, and then `docker run goss` in said container.

Since this issue is pretty old, curious if you already found an answer to this.

**Comment by CCFenner** [comment]
Meanwhile I managed to run `goss` in Docker Hub using a [docker-compose.test.yml](https://github.com/SAP/cloud-mta-build-tool/blob/master/docker-compose.test.yml) file.
If you like I can open a PR describing how to do this.

**Comment by aelsabbahy** [comment]
This seems like a cool idea for a blog post. So essentially you're using the Goss docker image and mounting it's volume in the test image?

Can you describe the usecases for automated repository tests and Goss? If you're not building a docker image what are you testing with it?

**Comment by CCFenner** [comment]
We *are* building an image on Docker Hub (in this case a build tool for cloud applications). In this context we use Goss to validate various assumptions regarding the image during the build. 

Using the `docker-compose` file our image is built and additionally the Goss executable is linked from the Goss container into the *service under test* along with the project repository containing the goss tests. Then a test command is executed, the *service under test* needs to exit with `0` to succeed the build.

**Comment by aelsabbahy** [comment]
This is really cool. I'm considering writing up a blog post on this. Let me know if this is something you're planning to write. Otherwise, I don't mind writing it and putting a note giving you credit for showing me this.

Thanks for the question / sharing the solution!

**Comment by CCFenner** [comment]
@aelsabbahy if this is not yet done I would start writing a blog now.

**Comment by aelsabbahy** [comment]
I have not written a blog post on this.

If you end up writing a blog post on this, please share the link here. :)

**Comment by CCFenner** [comment]
For now only available as a [Gist](https://gist.github.com/CCFenner/89710c3a74b4744eae9ead94931f15a5).
