### ISSUE TITLE
dgoss README references older goss version

### ISSUE THREAD

**Issue by jeffb4** [aelsabbahy/goss#470]
The dgoss README references `0.3.6` instead of `0.3.7` in the MacOS install instructions https://github.com/aelsabbahy/goss/blob/master/extras/dgoss/README.md#mac-osx

**Comment by aelsabbahy** [comment]
Reworded it to only be an example version rather than the latest.

**Comment by aelsabbahy** [comment]
Please reopen if the verbiage isn't clear.
