### ISSUE TITLE
IANA reserved port 1281 for a healthd 

### ISSUE THREAD

**Issue by bbaassssiiee** [aelsabbahy/goss#474]
In the default implementation port 8080 is used for `goss serve`. Port 8080 is a reserved port for  WWW caching service.

I suggest to use port 1281 (healthd) for nicer output in `netstat`:

```
tcp6       0      0 [::]:healthd            [::]:*                  LISTEN
```

The same in `ss`

```
LISTEN     0      128                                           :::healthd                                                     :::*
```

**Comment by aelsabbahy** [comment]
Users can override the default port with ease.

8080 was used since it's a fairly common port. I assume most users will override the port and/or /healthz endpoint.
