### ISSUE TITLE
gossfile execution order - is it possible 

### ISSUE THREAD

**Issue by milind69** [aelsabbahy/goss#475]
I have two gossfiles I am calling from another one  but I need it to follow the order can it be possible to put some order on test conditions 
1st goss file contain a 
file: test 
2nd goss file contain a 
command:
I need command to be executes first

**Comment by sshipway** [comment]
Oh I just submitted feature request #485 for this

**Comment by aelsabbahy** [comment]
It is not possible to define the test order in goss. Each test is run in isolation and in parallel by default and is intended to be stand-alone. Goes is not intended to change system state with the `command` test.

Closing this ticket to consolidate with the feature request here #485.

See my response on possible workarounds for some use-cases here: https://github.com/aelsabbahy/goss/issues/485#issuecomment-563002353
