### ISSUE TITLE
Implement netfilter verification

### ISSUE THREAD

**Issue by mgier** [aelsabbahy/goss#479]
Hi @ all,

is there a way to check if all ports on a machine are closed except a few desired ones?

This would be a nice feature regarding a permanent security check of servers. 

Thank you!

**Comment by jpds** [comment]
I was going to file an issue like this; better title would be: "Implement netfilter verification"

**Comment by mgier** [comment]
You're right, done!

**Comment by aelsabbahy** [comment]
Can you expand a bit more on how this syntax would look like? I haven't messed with Linux firewalls for a while, so not sure what's out there: iptables, firewalls, ufw.

Kind of undecided on this feature if there's a lot of variations. Curious on how Goss native would look vs using the `command`.
