### ISSUE TITLE
dynamic values in file contains

### ISSUE THREAD

**Issue by krimitalel** [aelsabbahy/goss#480]
How can we validate some parameters dynamically in some config file.  
for example :

redis.conf
bind {{ eth2.ip_address }}

**Comment by mattwilmott** [comment]
There would need to be a source of facts for this to work cleanly. Perhaps use Puppet's facter or Ansible setup to determine the value and populate the goss template

**Comment by aelsabbahy** [comment]
You should be able to use the `--vars` flag for this.

See [Templates](https://github.com/aelsabbahy/goss/blob/master/docs/manual.md#templates)
