### ISSUE TITLE
Document how user: exists checks for existence

### ISSUE THREAD

**Issue by colearendt** [aelsabbahy/goss#482]
We are seeing a case where testing for user existence fails if the user is defined by an external system (i.e. LDAP). The user exists from the system's perspective, but not from the perspective of goss. If this could be remedied or the documentation improved to clarify how to reproduce / sanity check goss's response, that would be great!

```
user:
  jen:
    title: sssd_user_exists
    exists: true
```

This fails, but `getent passwd jen` succeeds and returns information. I presume `goss` is doing some type of check for pure system accounts (in `/etc/passwd`, for instance).

**Comment by aelsabbahy** [comment]
How does the verbiage in #482 look?

**Comment by aelsabbahy** [comment]
Thanks for the feedback, I've merged in updated documentation.

Feel free to reopen this ticket if the new documentation isn't clear enough with suggestions on how to best improve it.
