### ISSUE TITLE
Feature: Support for podman / buildah

### ISSUE THREAD

**Issue by dschier-wtd** [aelsabbahy/goss#507]
Hi,

I am using podman for some time now and am starting to use goss as validator / verifier for ansible and my containers. For docker, you have the dgoss, dcgoss wrapper, which is already working fine.

I request to either:

- extend the existing wrapper to support podman via cli switch
- add pgos and bgoss for podman and buildah
- provide cgoss, which is a general container+goss wrapper with support for docker, podman, etc.

After a confirmation of one of the above, I can help to develop this wrapper in the way, you prefer.

**Comment by aelsabbahy** [comment]
There's also a kgoss in the works: https://github.com/aelsabbahy/goss/pull/465

I'm fine with adding a new script in the extras folder. My plan is to add a top level readme that explains what each script does and links to their individual readme.

For now, `dgoss` will be the only officially supported one, but I would love for the extras folder to grow with the community. 

As I'm sure you've noticed dgoss is just a simple ~100line bash script. These scripts are meant to be a useful reference of how easy it is to use goss with containers. If down the road there's a lot of similarities, maybe a new more complex wrapper can be created in something other than bash.

Summary: I'm fine with adding more scripts as they provide simple and isolated examples of goss working with that tool.

**Comment by aelsabbahy** [comment]
Got a chance to play with podman today. Seems like it can be a drop-in replacement as it pertains to dgoss. Also, from what little I read about it so far I like it more than docker from a security standpoint.

Does it make sense to modify dgoss to:
1. Allow the user to set the container manager executable through environment variable.
2. If not set, detect docker, podman commands?

Haven't tested this yet, but curious on your take.

Haven't looked at buildah yet.. where does it fit with dgoss?

**Comment by daniel-wtd** [comment]
Hi, unfortunately I was working on some other issues over at pcp, podman, dnsmasq and will check the podman integration again. After having a look at the dgoss, it seems like we can have some kind of drop-in replacement. On the other hand, podman has some differences like seperate namespaces for different users and mounting stuff on selinux enabled systems (which is very common on fedora, centos, redhat) is handled slightly different.

I think, during the next 2-3 weeks or so, I will have some code in place to play with.

**Comment by jacobsin** [comment]
Yup - exposing it via env var e.g. `DOCKER_BIN=${DOCKER_BIN:-docker} works well for us with podman 1.6.4

Will see if a PR can be submitted

**Comment by daniel-wtd** [comment]
At least since podman 2.x, we will see even socket compatability.
