### ISSUE TITLE
Feature: Documentation should point to latest install

### ISSUE THREAD

**Issue by daniel-wtd** [aelsabbahy/goss#521]
**Describe the feature:**

Updating the README.md (Installation section) with the proper links to the latest release would improve the usability a lot. The described solution can also improve the install script and avoid copy/paste confusion.

**Describe the solution you'd like**

Update the links to _VERSION_ according to <https://help.github.com/en/github/administering-a-repository/linking-to-releases>

```
/owner/name/releases/latest/download/asset-name.zip
```

**Describe alternatives you've considered**

Alternatively, you can link to the latest release version (v0.3.8 atm).

**Comment by aelsabbahy** [comment]
Whoa.. wonder if this is new-ish or if it was always there. I was looking for a link like that from github.

Definitely like it for the install script. For documentation/readme thinking both are important latest and specific version? What are your thoughts on the readme.

Marking this as approved, I'll merge PRs for this if someone submits it, if not.. I'll eventually get around to it as it's a small change with nice benefits.

**Comment by johnk-novu** [comment]
PR opened for this: https://github.com/aelsabbahy/goss/pull/567

**Comment by aelsabbahy** [comment]
Closed by #567
