### ISSUE TITLE
Add a documentation on how to extend Goss with custom validation

### ISSUE THREAD

**Issue by Mogztter** [aelsabbahy/goss#54]
I think it would be useful to write a documentation about how to extend Goss with custom validation.

**Comment by aelsabbahy** [comment]
If you mean how to add a new validation and compile a new version of goss, I can document that.

If you mean a custom validation at runtime, goss doesn't support that unfortunately.

**Comment by Mogztter** [comment]
> If you mean how to add a new validation and compile a new version of goss, I can document that.

Yes that's what I meant:smile:

**Comment by Mogztter** [comment]
Just try Goss on one of our environment and it's working great! Really nice tool :+1: 
I've never code in Go but If you need help with the documentation, just ask.

**Comment by aelsabbahy** [comment]
The main problem currently is that the code is very verbose and repetitive. There are some enhancements that I have in mind to simplify this, but want to get a better understanding of golang best practices before refactoring. I'll document the current state, with the assumption that'll get simplified later.

Out of curiosity what kind of custom validator where you looking to add? I'm probably only going to accept checks into the project that are generic enough to have a wide use-case. Would like to keep the tool focused in scope. as much as possible.

**Comment by Mogztter** [comment]
> Out of curiosity what kind of custom validator where you looking to add?

I'm working for a client with a *lot* of Bash scripts that validate technical requirements.
Most of the time, these scripts are just checking user, group, process, port... but I won't be surprised to find some twisted logic that require a custom validator. Even if I could probably write a script with this twisted logic and use `command` to check the return code.

> I'm probably only going to accept checks into the project that are generic enough to have a wide use-case.

Fair enough :wink: 

> Would like to keep the tool focused in scope. as much as possible.

I'm gonna try.
We do have some checks about logical volume. Is that something you will be interested in ? 

```yml
lvm:
  /dev/mapper/lv_data:
    size:
      gt: 10G
```

We are also using `find -perm` to check permissions recursively (for security reason). One use case is to make sure that file under a directory are only readable/writable/executable for the owner.
Not sure about the right way to describe this state...

**Comment by aelsabbahy** [comment]
So sometime in the next two weeks, I'll document some high level guidelines on what to think about when creating a new validation type. I'll also do a simple custom validator so future developers can see the process end-end.

That said, some initial thoughts on guidelines:
* Can it be done using golang, without depending on external tools?
  * This is preferred as it allows for faster execution time, and uses less resource allocation when run in parallel.
  * Currently goss only runs the following external commands:
    * Package managers: rpm, dpkg-query, etc..
    * `service service_name status`

* Does it require root/special user access?

* Does it have wide application, I follow the 80/20 rule here. Mostly to keep maintenance easier

* Can it be done simply with `command`?
  * If yes, any benefit to having a dedicated validator for it?

* Is it easy to test in ci?
  * Currently docker is used, so if something needs more than docker the test suite needs to be modified for it

Another limitation is currently an attribute is matched up against what is found on the system, there isn't support for nested attributes yet in goss, so this would need to be built in if we decide to add checkers that need them.

Having said that, looking at your examples above:

## lvm

* Can it be done using golang? not sure, but probably
* Does it require special user access? yes
* Wide application? yes, lvm is pretty common
* Can it be done simple with `command`?
  * yes: `blockdev --getsize64 /dev/mapper/lv_data`
  * or:  `lvs -o lv_size /dev/mapper/fedora-home --noheadings`
* Any benefit to having a dedicated validator for it?
  * Maybe if it's made more generic and supports more than just size, see below
* Is it easy to test in ci?
  * not sure..

```
blkdev:
  /dev/mapper/lv_data:
    size:
      # "10G" wouldn't work out the box, this would either need to be modified to
      # something like this:
      gt: 10737418240
      # or:
      gt: 10
    fs_type: xfs
```

## Limits
* Can it be done using golang? probaly
* Does it require special user access? yes
* Wide application? yes
* Can it be done simple with `command`?  yes, but probably requires `su` or `sudo`
* Any benefit to having a dedicated validator for it?
  * probably, would need to build nested dict object matcher
* Is it easy to test in ci?
  * Probably


I Would be open to a golang version of both of those, if it needs to rely on an external command I woudld be less open to it, but not 100% against if it works cross platform and provides multiple attributes to test against.

**Comment by Mogztter** [comment]
Hey @aelsabbahy 

> So sometime in the next two weeks, I'll document some high level guidelines on what to think about when creating a new validation type. I'll also do a simple custom validator so future developers can see the process end-end.

Excellent!
Thanks for these guidelines, this is really useful.

> Another limitation is currently an attribute is matched up against what is found on the system, there isn't support for nested attributes yet in goss, so this would need to be built in if we decide to add checkers that need them.

I'm not sure to understand what you mean ? Do you have an example ?

> I Would be open to a golang version of both of those, if it needs to rely on an external command I woudld be less open to it, but not 100% against if it works cross platform and provides multiple attributes to test against.

Ok.
Once your "simple custom validator" will be created I will try to find time to work on that!

**Comment by aelsabbahy** [comment]
Apologies for not following up on the documentation yet, haven't had much free time and I've been prioritizing bug fixes over this.

> I'm not sure to understand what you mean ? Do you have an example ?

Currently there's support for this
```yaml
/tmp:
  attr: attr_value
```

but not nested attributes like:

```yaml
/tmp:
  attr:
    nested_attr: attr_value
```
