### ISSUE TITLE
Ëxample of how to use CONTAINER_LOG_OUTPUT

### ISSUE THREAD

**Issue by simon-k** [aelsabbahy/goss#541]
It would be nice with an example on how to use CONTAINER_LOG_OUTPUT. I've tried, but haven't made it work. 

I would like the output in the container to end up in a log file on the host so I can see why tests are failing.

**Comment by aelsabbahy** [comment]
What have you tried so far? It should just work with setting the environment variable.

```
CONTAINER_LOG_OUTPUT=dgoss_run.log dgoss run ...
```

**Comment by aelsabbahy** [comment]
Feel free to re-open if you feel your question wasn't answered.
