### ISSUE TITLE
Can we support UDP in addr test

### ISSUE THREAD

**Issue by weakiwi** [aelsabbahy/goss#542]
**Describe the feature:**
Addr resource support udp address
**Describe the solution you'd like**
specify Localaddr network type by user or according to target

**Describe alternatives you've considered**
https://github.com/aelsabbahy/goss/blob/6abda7e83d9d35129f37278ef5ba8cf864b8be95/system/addr.go#L43 In this line, localaddr use TCPAddr. According to offical docs https://golang.org/pkg/net/#Dialer, `LocalAddr ` should `be of a compatible type for the network being dialed`

**Comment by aelsabbahy** [comment]
released
