### ISSUE TITLE
Community feedback, contribution workflow

### ISSUE THREAD

**Issue by aelsabbahy** [aelsabbahy/goss#543]
This is meant as a discussion to follow up on #411. For those interested in getting more involved with goss, I am interested in the following:

1. Now that there is a [CONTRIBUTING.md](https://github.com/aelsabbahy/goss/blob/master/.github/CONTRIBUTING.md), issue/pr templates, and approval process in place. Is there anything currently lacking in the goss contributing process?

2. Are there some high level directions the community would like to see in goss. If so, the conversation can start here and can fork off into dedicated focused discussions.

3. If you are interested in getting more involved with goss, how would you like to be more involved? And what about the goss process (1 above) is impedes that?

**Comment by pedroMMM** [comment]
Thank you, @aelsabbahy, for all you have done for everyone. I love to keep up my involvement in Goss to give back to OSS.

The main issue with Goss is the comatose community. The activity keeps the people that are around engaged which then attracts more people.

@aelsabbahy should ask individuals directly for help, this usually helps to get people engaged.

An unstructured communication system for more casual conversation to revitalize the community, this communication avenue is also better for questions.

PRs turned around quickly helps to keep contributors engaged. I understand that @aelsabbahy can't be around all the time. He has a life of his own and maintainer fatigue is a big problem in OSS. Eventually, an OSS project evolves from a single maintainer into a maintainer team.

Once an active team of users, contributors, and maintainers exist the technical problems become actionable.

**Comment by aelsabbahy** [comment]
Hey @pedroMMM, thank you for all your contributions to goss recently, they are all great additions to the tool.

> An unstructured communication system for more casual conversation to revitalize the community, this communication avenue is also better for questions.

This is an interesting idea, I would be curious on:
1. Is there a large enough user-base to make this worthwhile?
2. How involved would I have to be in this chat. To be 100% transparent, I probably won't be available to answer questions in a timely manner. However, it may provide a communication forum for users to help each other.
3. I've recently added the `question` tag.. and while it's less than ideal. It's hopefully a step in the right direction.
4. I can create a slack workspace if this is something that would help.

> PRs turned around quickly helps to keep contributors engaged. I understand that @aelsabbahy can't be around all the time. He has a life of his own and maintainer fatigue is a big problem in OSS. Eventually, an OSS project evolves from a single maintainer into a maintainer team.

I'm hoping the new contributing/workflow changes help with this. there should be a clearer path to go from idea to PR to release. I would like to try this workflow for a few more months to see how it works out. If it doesn't then maybe start looking at transitioning goss into a maintainer team.

**Comment by pedroMMM** [comment]
> 1. Is there a large enough user-base to make this worthwhile?

Right now, no. The goal of the unstructured communication system suggestion is to help build a community.

> 2. How involved would I have to be in this chat. To be 100% transparent, I probably won't be available to answer questions in a timely manner. However, it may provide a communication forum for users to help each other.

I wouldn't expect you to! As you mention with a few people around we should be able to turn around questions and requests without you.

> 3. I've recently added the `question` tag.. and while it's less than ideal. It's hopefully a step in the right direction.

I look into the issues every few days and everyone once in a while I find questions that I could have answered but was just too slow. To be frank I feel like I am either using GitHub notifications wrong or/and the system isn't designed for fast turn around of issues.

> 4. I can create a slack workspace if this is something that would help.

We can at least experiment.

> > PRs turned around quickly helps to keep contributors engaged. I understand that @aelsabbahy can't be around all the time. He has a life of his own and maintainer fatigue is a big problem in OSS. Eventually, an OSS project evolves from a single maintainer into a maintainer team.
> 
> I'm hoping the new contributing/workflow changes help with this. there should be a clearer path to go from idea to PR to release. I would like to try this workflow for a few more months to see how it works out. If it doesn't then maybe start looking at transitioning goss into a maintainer team.

I am not convinced by the new contributing/workflow changes, while a step in the right direction it's not enough. I would like nothing more than been wrong. Now with that said waiting for a bit is more than fair.

**Comment by belfast77** [comment]
I'd be very interested in the slack channel and helping to spread the word.

I'm not a dev, I'm a user and a fan.

In two weeks we are holding a meetup and a topic of using Goss to test deployments made with ansible.
https://www.meetup.com/Hampshire-Everything-as-Code-Automation/events/268954548/

Then Later in the year @ 
https://www.meetup.com/Ansible-London/

Happy to promote the Slack channel at both.

There is also the Ansible Molecule
Molecule project is designed to aid in the development and testing of Ansible roles.

Goss is a validator for Molecule and they are also seeking maintainers to make sure it stays as part of the project.
https://github.com/ansible-community/molecule-goss/

**Comment by fbartels** [comment]
> I can create a slack workspace if this is something that would help.

Before going with a closed source service like Slack, please consider something more rooted in the OSS eco system like Matrix/Riot. Riot also has a feature called "communities" which helps grouping channels.

**Comment by petemounce** [comment]
gitter.im is pretty low-friction, free for OSS, and doesn't require a client-install.

**Comment by petemounce** [comment]
There are a set of github workflow automations that are low-friction to set up, available via https://probot.github.io/apps/.

These are good for reducing maintainer toil:

* https://probot.github.io/apps/first-timers/
* https://probot.github.io/apps/reaction/
* https://probot.github.io/apps/stale/
* https://probot.github.io/apps/triage-new-issues/

**Comment by pedroMMM** [comment]
I fully understand the reflex to just use Slack and honestly, it's a respectable choice. The low friction and familiarity are excellent motivators. The only choice I am not comfortable with is [Gitter](https://gitter.im) based on bad experiences in the past.

But if we want to embrace OSS, there are some great options out there. From talking with a co-worker that is active on the Scala community she suggested using [Zulip](https://zulipchat.com/for/open-source/ ) based on their [discussions](https://users.scala-lang.org/t/can-we-have-an-official-scala-discord-server/5157/47). 

@belfast77 I would like to see the materials from that presentation as well the reactions and comments of your local community 👍 

[I will actually be doing a presentation next week as well on Goss to one of the Baltimore Meetups I frequent on testing Packer with Goss.](https://www.meetup.com/Baltimore-DevOps-Meetup/events/268477682/)

**Comment by aelsabbahy** [comment]
Whoa, small world, I'm in DC that week, but leaving on the 11th. If you're local to the DC area maybe we can meet up.

I'll look at the chat options and get back to everyone here. I'm not as adamant about OSS personally. Convenience and ease of use is what's most important to me.

**Comment by petemounce** [comment]
We use goss for packer validation too.

**Comment by pedroMMM** [comment]
@aelsabbahy I am just north of Baltimore, we can try to schedule something 👍

**Comment by aelsabbahy** [comment]
Added stale bot, I guess the only to-do item left on this is to add a slack channel. Anything else?
