### ISSUE TITLE
exact/strict matching using contents in a file.

### ISSUE THREAD

**Issue by shan100github** [aelsabbahy/goss#556]
I would like to know how we can do the exact matching of content through goss.
file content:
```*/5 * * * * /usr/local/tmp/tmp1.sh exec > /dev/null 2>&1```

currently, I am trying to test with the following goss.yaml
```
file:
  /var/spool/cron/temp:
    exists: true
    filetype: file
    contains:
    -  "*/5 * * * * /usr/local/tmp/tmp1.sh exec > /dev/null"
```
I am expecting this to fail because goss.yaml doesn't have `2>&1`. 
If it's not possible through file checking, how we can achieve it.

I have gone through templates & pattern matching but finding difficult to understand it.
Sorry for the noise, looking forward to get some guidance.

**Comment by shan100github** [comment]
Thanks for your quick reply & it worked.

**Comment by aelsabbahy** [comment]
Awesome! :)
