### ISSUE TITLE
Linux command output display request as a part of goss command test result.

### ISSUE THREAD

**Issue by shan100github** [aelsabbahy/goss#559]
**Describe the feature:**
Refer: https://github.com/aelsabbahy/goss/issues/557
Currently, file comparison/validation can be performed through [goss command](https://github.com/aelsabbahy/goss/blob/master/docs/manual.md#command). Failure details are not displayed during command execution.

Sample execution of goss command to `diff /tmp/file1 /tmp/file2` 
```
command:
  diff:
    exit-status: 0
    exec: "diff /tmp/file1 /tmp/file2"
```
during the success scenarios it's fine, But the output displayed during failure scenarios is not providing details about failure.

on failure following output is displayed by goss.
```
$>goss v -f tap
1..1
not ok 1 - Command: diff: exit-status: doesn't match, expect: [0] found: [1]
```
**Solution suggestion**
During linux command `diff /tmp/file1 /tmp/file2`execution in terminal displays following content. If we can display following content as goss test result it will be easier for enduser to know failures 
```
$>diff /tmp/file1 /tmp/file2
2c2
< am in file1
---
> am in file2
```

**Describe alternatives considered**

No alternatives considered currently, using goss command to perform file diff.

**Comment by petemounce** [comment]
Maybe use a package to generate diffs; https://godoc.org/github.com/pmezard/go-difflib/difflib I think. Windows doesn't natively provide that tool :(

**Comment by aelsabbahy** [comment]
consolidating with https://github.com/aelsabbahy/goss/issues/483
