### ISSUE TITLE
http resource - Host header not set

### ISSUE THREAD

**Issue by johnk-novu** [aelsabbahy/goss#564]
**Describe the bug**
Go's `net/http` library excludes/skips setting certain request headers, including `Host`.

**How To Reproduce**
Write a `goss` test that relies on a host header being set.
See https://gist.github.com/johnk-novu/fd3671819c59da227296c54ef393411c for example.

**Expected Behavior**
`Host` header is presented to the webserver.

**Actual Behavior**
No `Host` header(s) are presented to the webserver.

**Environment:**
 - Version of goss: v0.3.10 / built off `master`
 - OS/Distribution version (if applicable): MacOS Mojave 10.14.5

**Comment by johnk-novu** [comment]
PR in the works, will re-target to this repo when it is closer to being "ready"

https://github.com/johnk-novu/goss/pull/1

**Comment by johnk-novu** [comment]
PR open https://github.com/aelsabbahy/goss/pull/565

Struggling to get test running locally due to some laptop issues, getting Go setup on another machine to run tests.

**Comment by johnk-novu** [comment]
Confirmed `make test-all` passes. PR should be good to go.

**Comment by aelsabbahy** [comment]
Closed by #565
