### ISSUE TITLE
Support querying Pacman package manager

### ISSUE THREAD

**Issue by siddharthist** [aelsabbahy/goss#57]
The package resource could easily add support for the `pacman` package manager used in Arch Linux. If we add support, I'll switch distributive's package check to use goss's code. Would you merge a PR to this effect?

**Comment by aelsabbahy** [comment]
Yeah, I would merge Pacman support. I just ask that you add an arch docker image/tests in the PR.

**Comment by aelsabbahy** [comment]
Released in [v0.1.4](https://github.com/aelsabbahy/goss/releases/tag/v0.1.4)
