### ISSUE TITLE
Difficult Makefile

### ISSUE THREAD

**Issue by langston-barrett** [aelsabbahy/goss#58]
The Makefile for goss depends on `goupx`, which probably introduces unecessary complexity. A few mb here or there isn't a big deal to anyone who can't run it themselves.

Additionally, `make` depends on Docker access. Most developers will run `make` as an unpriveleged user; the only secure access to `docker` can be through `sudo`. However, if you run `sudo make`, your GOPATH and GOROOT probably aren't set correctly to build `goss`.

**Comment by siddharthist** [comment]
I fixed the second issue by replacing `./test.sh` with `sudo ./test.sh` on [these lines](https://github.com/aelsabbahy/goss/blob/d28f3cc6d708fb012ea614acf712eb56712a7de3/Makefile#L45-L52).

**Comment by aelsabbahy** [comment]
If it doesn't break the travis build I'm fine with the fine with the sudo change.


Goupx can be moved to only run when doing `releases`. I'll probably drop goupx when the Golang 1.7 comes out.
