### ISSUE TITLE
New release?

### ISSUE THREAD

**Issue by Agares** [aelsabbahy/goss#581]
Hey, it seems like there was a bunch of changes since the last release in february. Is there a plan to tag a new one?
I'm looking for a tag that'd include this commit: https://github.com/aelsabbahy/goss/commit/c8cd87bca11a48bd3d5273313c7a7a43cec85319, but I couldn't find any

**Comment by aelsabbahy** [comment]
dgoss gets released whenever goss itself is released. However, I never cut a release just for a dgoss change.

There will probably be a new goss release in the next two weeks or so. However, dgoss you can just grab the one from master at any time and it changes a lot more frequently than goss between releases.

**Comment by aelsabbahy** [comment]
I've updated the readme with instructions on how to install from master. This is what the install script does.

https://github.com/aelsabbahy/goss/blob/master/install.sh#L14
