### ISSUE TITLE
Is it possible to run dgoss test in Azure pipelines 

### ISSUE THREAD

**Issue by BeamerIsHere** [aelsabbahy/goss#587]
Hi All,
I've created a test script (goss.yaml) using dgoss and able to successfully test in local machine. Now I want to add this image build process and dgoss test in azure pipelines.  Is that possible?
A reply will be much appreciated!  

Thanks!

**Comment by aelsabbahy** [comment]
If it supports running the docker command, I don't see why not.

https://docs.microsoft.com/en-us/azure/devops/pipelines/ecosystems/containers/build-image?view=azure-devops#script-based-docker-builds

I would try the Ubuntu agent, you may also need to set GOSS_FILES_STRATEGY  depending on how azure does things (never used azure pipelines myself to know for sure)
