### ISSUE TITLE
Support Flatcar as one of Distros

### ISSUE THREAD

**Issue by dongsupark** [aelsabbahy/goss#596]
**Describe the feature:**
Support [Flatcar Container Linux](https://www.flatcar-linux.org/) as one of the distros in Goss. 

At the moment, when goss runs with a config starting with `package:`, it fails to run, because Flatcar is not in the [list of support distros](https://github.com/aelsabbahy/goss/blob/d1e9f590bb65196a46df530b0af3cc3ecd5fd4fa/system/system.go#L184). As a result, goss tries to simply run rpm commands, which obviously fails on Flatcar, because Flatcar does not have any package manager.

**Describe the solution you'd like**

Make goss detect Flatcar correctly.
And if it is Flatcar, then do not fail, just silently skip package installations.

**Comment by aelsabbahy** [comment]
I'm fine with erroring out with a "Not implemented" but silent success with a skip seems misleading and could allow for false positives.
