### ISSUE TITLE
dcgoss: is this really the way it should be working?

### ISSUE THREAD

**Issue by dakky** [aelsabbahy/goss#598]
**how does dcgoss work at the moment?**
It starts a single service from the complete docker-compose setup and is running the goss tests inside this single service

**how should it be working IMHO**
It should start **all** services in the compose setup and then run the tests in the wanted service.

Why? this allows to test more complex setups, like "database <-> service" setups. 

So this leads me to the question, if I should create a PR for this issue, implementing this feature. Not shure if there is some kind of backward compatibilty, which should be regarded.

**Comment by fbartels** [comment]
IMHO its fine like it is. Yes, it starts just a single server (the service to be tested), but you can define dependencies in docker-compose so all the services required to run your tests should come up with it.

To me it sounds like you are missing these "depends" instructions in your compose file.

This is how I am using dcgoss: https://github.com/zokradonh/kopano-docker/blob/e99c524d4629899e02357bc573f0093d9fc74719/Makefile#L457-L469

**Comment by aelsabbahy** [comment]
@dakky does @fbartels suggestion resolve the issue for you?

**Comment by dakky** [comment]
jep kind of ;)
