### ISSUE TITLE
goss serve: render response format according to content negotiation

### ISSUE THREAD

**Issue by petemounce** [aelsabbahy/goss#615]
**Describe the feature:**
`goss serve` can respond to the `Accept` http header on incoming requests, and choose the `Content-Type` for the response if possible based on that.

This will allow `goss serve` more flexibility at run-time; previously, if more than one output format was wanted, one endpoint process+port per output format would need to be set up.

**Describe the solution you'd like**

(This is a retroactive ticket to collect together the PRs as much as describe the work)

This is the order to merge the PRs in:

1. #606 - add some unit test coverage
1. #608 - add some integration test coverage
1. #609 - add the content negotiation (with documentation)
    * this is a stacked PR on top of #606 and should merge cleanly.

(Afterwards, #586, but since #608 adds a new script, I'll fix that up inside that PR once #608 is merged)

**Describe alternatives you've considered**
Setting up one endpoint per desired goss format.

**Comment by petemounce** [comment]
@aelsabbahy this issue acts as a "main entry point" for the cluster of PRs I've made; it overrides what I said about order in https://github.com/aelsabbahy/goss/pull/609#issuecomment-690095037 and also answers your question in https://github.com/aelsabbahy/goss/pull/608#issuecomment-691151429.

**Comment by aelsabbahy** [comment]
Didn't forget about this, just fell behind this weeekend on this. I'll try my best to review/merge all this before wed.

**Comment by aelsabbahy** [comment]
> This is the order to merge the PRs in:

> #606 - add some unit test coverage
#608 - add some integration test coverage
#609 - add the content negotiation (with documentation)
this is a stacked PR on top of #606 and should merge cleanly.
(Afterwards, #586, but since #608 adds a new script, I'll fix that up inside that PR once #608 is merged)

606 done/merged
608 doesn't fail build when tests fail, I don't think that was intentional (I've commented on the PR)
609 needs a rebase

**Comment by aelsabbahy** [comment]
Everything is merged except #609

It's currently failing the build, once that's green/merged this ticket can be closeod

**Comment by petemounce** [comment]
@aelsabbahy thanks! I've fixed #609; I'd left in a deliberate test failure to debug a thing :(
