### ISSUE TITLE
Test if PHP module is available

### ISSUE THREAD

**Issue by Yamakasi** [aelsabbahy/goss#617]
Is it possible to see if a module in PHP is available after installing/compiling ?

I thought even of grep for the php -m command but I'm not sure if this is possible.

Nice tool, thanks!

**Comment by aelsabbahy** [comment]
It would have to be through the [command](https://github.com/aelsabbahy/goss/blob/master/docs/manual.md#command) test.

I haven't touched php in a long long time, but if you have a command output example, and what you're trying to assert against it, I can help out.

**Comment by Yamakasi** [comment]
> 
> 
> It would have to be through the [command](https://github.com/aelsabbahy/goss/blob/master/docs/manual.md#command) test.
> 
> I haven't touched php in a long long time, but if you have a command output example, and what you're trying to assert against it, I can help out.

I'm going to test out the command first and report back. PHP basics are simple, you won't ever forget them... maybe you are a little bit rusty in trusting yourself you still can do it ;)
