### ISSUE TITLE
No goss.yaml file created after exit

### ISSUE THREAD

**Issue by Yamakasi** [aelsabbahy/goss#618]
**Describe the bug**
After exit a dgoss started container there is no goss.yaml created in the folder where I run the dgoss container... command in

**How To Reproduce**
dgoss edit -p 8080:80 nginx:1.11.10
goss a file /var/log/nginx/access.log /var/log/nginx/error.log
goss a process nginx
goss a port 80
goss a package nginx
goss a http http://localhost
exit

**Expected Behavior**
Have a goss.yaml available in the same folder after exit

**Actual Behavior**
No goss.yaml avaialble in folder after exit

**Environment:**
 - Version of goss: # goss -v > goss version v0.3.13
 - OS/Distribution version Ubuntu 20.04

**Comment by aelsabbahy** [comment]
Interesting. Can you provide the full output?

for example:
```
# This is on host
$ dgoss edit nginx:1.11.10
INFO: Starting docker container
INFO: Container ID: e257c0a9
INFO: Run goss add/autoadd to add resources
# pwd
/goss
# ls goss.yaml
ls: cannot access goss.yaml: No such file or directory
# goss a process nginx
Adding Process to './goss.yaml':

nginx:
  running: true


# ls goss.yaml
goss.yaml
# exit
INFO: Copied '/goss/goss.yaml' from container to './goss.yaml'
INFO: Deleting container

# This is on host
$ ls goss.yaml
goss.yaml


Also if you don't mind can you give me the output of md5sum $(which dgoss)

**Comment by Yamakasi** [comment]
@aelsabbahy I will,need to do some checks.

If I do a `goss autoadd nginx` then it writes one on exit.
