### ISSUE TITLE
Work with go tool

### ISSUE THREAD

**Issue by langston-barrett** [aelsabbahy/goss#62]
The `go build` command should work for all go packages, goss isn't doing anything particularly difficult in the Makefile that couldn't be ported to the go tool.

**Comment by aelsabbahy** [comment]
There's nothing stopping you from using `go build` I'm not sure I follow what the issue is here?

**Comment by siddharthist** [comment]
Hmm, maybe it's a problem in my environment? I get 
```
$ go build -o goss-bin .
$ ./goss-bin  
zsh: permission denied: ./goss-bin
$ chmod +x goss-bin 
$ ./goss-bin 
./goss-bin: line 1: syntax error near unexpected token `newline'
./goss-bin: line 1: `!<arch>'
```

**Comment by aelsabbahy** [comment]
cd cmd/goss first, then run `go build`

I need to move everything in the top level directory into a subfolder and bring cmd/goss up to the top level directory, this will make goss easier to `go get` also.

**Comment by siddharthist** [comment]
@aelsabbahy Sounds good to me :) thank you!
