### ISSUE TITLE
Add goss to NixOS packages

### ISSUE THREAD

**Issue by karantan** [aelsabbahy/goss#620]
Hey, I love goss tool but because I'm using NixOS servers I had to fork it and made a few changes to the code. Mainly I had to add some required .nix files so that NixOS can compile the package and use it a system package.

This was the PR: https://github.com/karantan/goss/pull/3

Is there any interest to have this upstream? We would basically just need to add those `*.nix` files and add a `make nix-install` command. 

Maybe also update CI.

**Comment by aelsabbahy** [comment]
How does nixos add other go libraries/software.

I know nixos tends to be pretty hermetic with its builds, but I also don't see *.nix files in most go repos.

@copumpkin I would love your thoughts on this, you're the only Nixos guru I know personally. :)

**Comment by karantan** [comment]
> How does nixos add other go libraries/software.

In the project you need to have a `default.nix` file (e.g. https://github.com/karantan/goss/pull/3/files#diff-245563af9e34754739b12b294f3324c1d42c116ace7ce8735e21dfbc82d8e064R1) which does it's magic when you have nix installed. Then when you do e.g. `nix-shell` it will build the project. In our case, it does the `make install` procedure (see https://github.com/karantan/goss/pull/3/files#diff-245563af9e34754739b12b294f3324c1d42c116ace7ce8735e21dfbc82d8e064R40). And that's it on the project side.

Next, we would need to create a PR to the [nixos pkgs repo](https://github.com/NixOS/nixpkgs/). So far I've made just one PR and it wasn't a golang project: https://github.com/NixOS/nixpkgs/pull/81492/files
But from what I'm seeing it's not that different.

Useful resources:
- https://nixos.org/manual/nixpkgs/stable/#sec-language-go
- https://github.com/kamilchm/go2nix

**Comment by aelsabbahy** [comment]
It doesn't make sense to me that a downstream project needs to manage the `default.nix` file.

Rpm, dev, pacman, or any other packages can be maintained outside of the goss repo.

 I don't know enough about the NixOs ecosystem myself (I've used it briefly many years back). I assume there's a way to import go packaged without having the maintainers of the git repos add an OS specific file.

Using helm for example: https://github.com/NixOS/nixpkgs/blob/master/pkgs/applications/networking/cluster/helm/default.nix

**Comment by karantan** [comment]
> It doesn't make sense to me that a downstream project needs to manage the default.nix file.

After reading my comment again it indeed doesn't make sense. I think I was describing my personal process of creating a nix package.

To clarify: You don't need to have a default.nix file in your project. You create one to test if the project can be packaged into a nix package. Once you do this, you simply move this default.nix file to nixos pkgs repository (where you create the PR).

I hope that makes more sense.

**Comment by aelsabbahy** [comment]
Makes sense. So I assume I can close out this ticket since there's nothing to do on the goss side?

Next steps: Anyone can submit the default.nix file to nixos pkg if they want it packaged there?

Let me know if there's anything else goss and Nixos specific.

**Comment by karantan** [comment]
> Makes sense. So I assume I can close out this ticket since there's nothing to do on the goss side?

I think so. We might need to update `Makefile` a bit.

I'll ask on IRC #nixos if anyone is willing to help with creating goss nix package.

**Comment by aelsabbahy** [comment]
Sounds great, looking forward to it!

If any changes are needed to the makefile just msg me on here or open a new ticket.

**Comment by Hyzual** [comment]
Hi, I've submitted a PR to nixpkgs here : https://github.com/NixOS/nixpkgs/pull/121497

I plan to also submit (and maintain) a package for `dgoss`
