### ISSUE TITLE
Removing alpha warning when flag is set

### ISSUE THREAD

**Issue by aelsabbahy** [aelsabbahy/goss#629]
**Describe the feature:**

Goss alpha is too noisy.

**Describe the solution you'd like**

Goss should not always display alpha warning, only when when use-alpha is not set.

**Comment by aelsabbahy** [comment]
@petemounce what's your opinion on this?

I finally got a chance to try the alpha version and maybe it's a little too chatty. I know I was the on who originally requested that.

**Comment by petemounce** [comment]
I totally agree.

**Comment by aelsabbahy** [comment]
Cool, marked it as approved
