### ISSUE TITLE
How to build RPM on OBS

### ISSUE THREAD

**Issue by brejoc** [aelsabbahy/goss#660]
I'm currently trying to get an RPM build ready for goss on [OBS](https://build.opensuse.org/). The first issue is that you can't just pull dependencies from the internet. Everything has to be included in the OBS repository. That's not that much of a problem, since I can just vendorize the dependencies. But building goss still doesn't work. My build command currently looks like this: `GO111MODULE=off CGO_ENABLED=0 go build -o goss ./...` 

And the output I get looks like this:

```
abuild@sierra:~/rpmbuild/BUILD/goss-0.3.15> GO111MODULE=off CGO_ENABLED=0 go build -o goss ./...
serve.go:12:2: cannot find package "github.com/aelsabbahy/goss/outputs" in any of:
	/usr/lib64/go/1.11/src/github.com/aelsabbahy/goss/outputs (from $GOROOT)
	/home/abuild/go/src/github.com/aelsabbahy/goss/outputs (from $GOPATH)
add.go:9:2: cannot find package "github.com/aelsabbahy/goss/resource" in any of:
	/usr/lib64/go/1.11/src/github.com/aelsabbahy/goss/resource (from $GOROOT)
	/home/abuild/go/src/github.com/aelsabbahy/goss/resource (from $GOPATH)
add.go:10:2: cannot find package "github.com/aelsabbahy/goss/system" in any of:
	/usr/lib64/go/1.11/src/github.com/aelsabbahy/goss/system (from $GOROOT)
	/home/abuild/go/src/github.com/aelsabbahy/goss/system (from $GOPATH)
add.go:11:2: cannot find package "github.com/aelsabbahy/goss/util" in any of:
	/usr/lib64/go/1.11/src/github.com/aelsabbahy/goss/util (from $GOROOT)
	/home/abuild/go/src/github.com/aelsabbahy/goss/util (from $GOPATH)
cmd/goss/goss.go:11:2: cannot find package "github.com/aelsabbahy/goss" in any of:
	/usr/lib64/go/1.11/src/github.com/aelsabbahy/goss (from $GOROOT)
	/home/abuild/go/src/github.com/aelsabbahy/goss (from $GOPATH)
resource/gomega.go:7:2: cannot find package "github.com/aelsabbahy/goss/matchers" in any of:
	/usr/lib64/go/1.11/src/github.com/aelsabbahy/goss/matchers (from $GOROOT)
	/home/abuild/go/src/github.com/aelsabbahy/goss/matchers (from $GOPATH)
abuild@sierra:~/rpmbuild/BUILD/goss-0.3.15> GO111MODULE=off CGO_ENABLED=0 go build -o goss ./...
```

So it seems like the rest of the folders is ignored. Is there any way to change that? Thanks!

**Comment by aelsabbahy** [comment]
`go build cmd/goss/goss.go` should work.

But the `goss -v` command won't work without properly passing that in.

The build is done through this script if you want to mimic the exact build parameters of the goss project itself:
https://github.com/aelsabbahy/goss/blob/620d32b003efedde8ee98e917005dd4642d88dc1/release-build.sh#L24-L27

**Comment by brejoc** [comment]
Thanks for the tip with the `-v` parameter. I'll add that once it is working. Unfortunately passing `cmd/goss/goss.go` is not that much of a difference, since 

```
abuild@sierra:~/rpmbuild/BUILD/goss-0.3.15> GO111MODULE=off CGO_ENABLED=0 go build -o goss cmd/goss/goss.go
cmd/goss/goss.go:11:2: cannot find package "github.com/aelsabbahy/goss" in any of:
        /usr/lib64/go/1.11/src/github.com/aelsabbahy/goss (from $GOROOT)
        /home/abuild/go/src/github.com/aelsabbahy/goss (from $GOPATH)
cmd/goss/goss.go:12:2: cannot find package "github.com/aelsabbahy/goss/outputs" in any of:
        /usr/lib64/go/1.11/src/github.com/aelsabbahy/goss/outputs (from $GOROOT)
        /home/abuild/go/src/github.com/aelsabbahy/goss/outputs (from $GOPATH)
cmd/goss/goss.go:13:2: cannot find package "github.com/aelsabbahy/goss/system" in any of:
        /usr/lib64/go/1.11/src/github.com/aelsabbahy/goss/system (from $GOROOT)
        /home/abuild/go/src/github.com/aelsabbahy/goss/system (from $GOPATH)
cmd/goss/goss.go:14:2: cannot find package "github.com/aelsabbahy/goss/util" in any of:
        /usr/lib64/go/1.11/src/github.com/aelsabbahy/goss/util (from $GOROOT)
        /home/abuild/go/src/github.com/aelsabbahy/goss/util (from $GOPATH)
```

Since the sources for goss are located in `~/rpmbuild/BUILD/goss-<version>` and `$GOPATH` points to `~/go`, Go seems not to be able to find the rest of the sources. I can copy the goss sources to the `$GOPATH`, but that taints the build environment even more. Not sure how a best practice approach would look like in such a case. :thinking:

**Comment by aelsabbahy** [comment]
I honestly have not attempted to build an RPM out of a Go project before. I'm sure there are guides out there on how to manipulate GOPATH and others correctly. There are enough Go-based projects that I would assume some relatively cookie-cutter patterns have come up.

Fedora typically keeps documentation on such patterns:
https://docs.fedoraproject.org/en-US/packaging-guidelines/Golang/


Seems OpenSUSE does the same?
https://en.opensuse.org/openSUSE:Packaging_Go

**Comment by brejoc** [comment]
I don't think manipulating the `GOPATH` is the problem here. I'm not sure if it should really be necessary to do that for goss itself. Sure, the (vendored) dependencies should be in the `GOPATH`, since the build environment is air-gapped. But why is `go build` not seeing the rest of the sources. Right now, if I understood that correctly, `go build` would fetch the sources of goss from GitHub in order to build goss which is localed on my filesystem already. That's a bit weird.

At least I can build the [package for Leap 15.2 and Tumbleweed](https://build.opensuse.org/package/show/home:brejoc/goss) with the work-around. Everything older won't work, since goss only seems to be compatible with Go >= 1.13.

**Comment by brejoc** [comment]
Alright, a colleague of mine found the solution. If we use `-mod=vendor` and `GO111MODULE=on`, then it's working when having vendorized dependencies.

```
GO111MODULE=on CGO_ENABLED=0 go build -o goss -mod=vendor cmd/goss/goss.go
```

**Comment by aelsabbahy** [comment]
Awesome, next time someone needs a vendored build I'll refer them to this ticket.

Thanks for posting your findings, really helps others.

**Comment by brejoc** [comment]
FYI: There are now builds for openSUSE Leap 15.2, 15.3, and Tumbleweed: https://build.opensuse.org/package/show/systemsmanagement/goss

Tumbleweed also ships goss in the default repos now. That means you can just do a `zypper in goss` without adding additional repos.

**Comment by aelsabbahy** [comment]
Awesome, looks great. Just read through the goss.spec file.. looks very clean.

Super cool that you got it into the official repos. Wonder what that process would look like for RHEL/Amazon Linux/Centos. :thinking:
