### ISSUE TITLE
Validating file size via inequality

### ISSUE THREAD

**Issue by benmangold** [aelsabbahy/goss#661]
**Describe the feature:**

Currently we can validate a file's size via an `= N` comparison.  This request is for validating a file's size via inequalities: `> N` or `< N`.

**Describe the solution you'd like**

I'm imaginging new options such as `file: /foo/bar: size_above: 100` or `file: /foo/bar: size_below: 100`.  Implementation-wise I think this is the simplest way to go.

Allowing one to pass an inequality to `file: /foo/bar: size:` like `file: /foo/bar: size: '> 100'` is another alternative, but would be more complex.

**Describe alternatives you've considered**

I'm sure there is a bash command which could be run to validate file size like this, very open to suggestions.  I'm also interested in contributing the change if approved.  Thanks!

**Comment by aelsabbahy** [comment]
You should be able to leverage [Advanced Matchers](https://github.com/aelsabbahy/goss/blob/master/docs/manual.md#advanced-matchers) to do what you want.

Example:
```yaml
file:
  /foo/bar:
    exists: true
    size:
      and:
        - le: 999999999
        - ge: 5
```

**Comment by benmangold** [comment]
Awesome!  Thanks for the prompt reply.  Closing this issue.

**Comment by aelsabbahy** [comment]
No problem, thanks for using goss and providing feedback!

On a related note to this.. I'm hoping within a month or two to release a major enhancement to the goss matches, see:
https://github.com/aelsabbahy/goss/pull/576

and Examples: https://github.com/aelsabbahy/goss/blob/add_transforms/examples/goss_awesome_gomega.yaml

Basically, being able to extract JSON and the ability to do numeric tests on strings, so "45" < 50 and "this nested JSON object's value is < 25" type tests.

Any feedback on that PR would be greatly appreciated.
