### ISSUE TITLE
the container failed to start, but not with directly docker run

### ISSUE THREAD

**Issue by Yamakasi** [aelsabbahy/goss#667]
My containers which I want to test fail to start and I cannot find a decent way to debug it.

Even when I build my own image out of an existing and working one like ubuntu:20.04 the dgoss container start fails.

```
INFO: Starting docker container
INFO: Container ID: f01c4eeb
INFO: Sleeping for 0.2
INFO: Container health
ERROR: the container failed to start
INFO: Deleting container
```

Just a `docker run -it --rm <imagename> bash` works fine for the same image where the test fails.

Anyone a clue ?

**Comment by aelsabbahy** [comment]
What's the `dgoss` command you're running?

Is it also `dgoss run -it <imagename> bash`?

Using the same command for both should give consistent results.

For debugging you can run `bash -x dgoss ...`

**Comment by Yamakasi** [comment]
Just a dgoss run but that one works on a default nginx container as well for an example.

So actually I'm figuring out why the -it is needed (now)
