### ISSUE TITLE
Export system/detectPackage, system/detectService, system/hasCommand

### ISSUE THREAD

**Issue by siddharthist** [aelsabbahy/goss#68]
I have a use case for this functions in distributive, I think when we fix [the FIXME in the comment](https://github.com/aelsabbahy/goss/blob/c94fac4026708d1a6b52b1323aad6a7434542bf0/system/system.go#L83), we should also export whatever solution we find.

**Comment by siddharthist** [comment]
I'm working on this refactor now.

**Comment by aelsabbahy** [comment]
Cool, thanks! I know we discussed a lot of features in the past, but my free time has gone down considerably as of late and I haven't been able to commit time :(
