### ISSUE TITLE
Is this project still maintained actively

### ISSUE THREAD

**Issue by obourdon** [aelsabbahy/goss#699]
Having  seen a lot of issues closed by stale-bot and being waiting for quite some time on PR approval not getting answers
I know we are all living difficult times but I'd really like to know if this project is still somewhat 'active' on the maintainer(s) side

many thanks for any answer

**Comment by ekelali** [comment]
Hello,

I'm a friend of the author/maintainer of goss. He recently started a new job and is working through getting legal approval to continue contributing to the project.

The project is not dead, just temporarily on hold while legal matters are worked out.

I have contribution access and can take over temporarily.

**Comment by obourdon** [comment]
Hello @ekelali and many thanks for this very good piece of news, I fully understand
All my best @aelsabbahy for the new job
Many thanks to both for all the great work
