### ISSUE TITLE
test cluster server

### ISSUE THREAD

**Issue by spham** [aelsabbahy/goss#705]
Hi
i wish test cluster of server on Git CI
what is the best practice ?

- launch one file testing many server ?
- or launch on every server different goss file 

In my case there have cluster in HA for rabbitmq. need test conncection and port open between each server

regards

**Comment by pedroMMM** [comment]
If I am understanding correctly you have several servers already up and running somewhere.

In this case you would have to establish a connection to each server and then run goss. So multiple files and multiple goss runs, one per server.

Let us know if this makes sense for you and your use case.
