### ISSUE TITLE
Travis CI

### ISSUE THREAD

**Issue by smebberson** [aelsabbahy/goss#72]
Great project. Are there any examples of running a bunch of Goss tests after push to Git on Travis CI?

**Comment by aelsabbahy** [comment]
Glad you're liking goss.

Goss itself runs goss tests against docker containers using travis-ci for integration testing.

Relevant bits:
* https://github.com/aelsabbahy/goss/blob/master/.travis.yml#L25
* https://github.com/aelsabbahy/goss/blob/master/Makefile#L46
* https://github.com/aelsabbahy/goss/blob/master/integration-tests/test.sh

Not the cleanest of code.. but it basically boils down to this:
```
# Download goss
wget http://url/to/goss

# Run container with goss + goss.json/yaml mounted
docker run -d -v /path/to/goss:/tmp/goss --name test_container some_container

# Run goss
docker exec test_container sh -c '/tmp/goss/goss -g /tmp/goss/goss.json validate'

# Cleanup
docker rm -vf test_container
```

Not sure if this is helpful, can you provide more details on what it is you're trying to do?

**Comment by aelsabbahy** [comment]
Haven't heard back from you, did my last comment answer your question sufficiently?

Also, for what it's worth there's `goss-ansible` and `kitchen-goss` (see readme) which might be useful for what you're trying to do.

Let me know if there's anything else I can do to help.

**Comment by aelsabbahy** [comment]
Closing this since I haven't heard back, feel free to re-open or open a new one if you have any more questions.
