### ISSUE TITLE
Support for  linux/arm64 architecture

### ISSUE THREAD

**Issue by tnaroska** [aelsabbahy/goss#722]
**Describe the feature:**
Goss currently provides 32bit arm binaries in the release but not arm64.

**Describe the solution you'd like**
- add linux arm64 to the supported architectures
- provide binary builds for arm64 in the GitHub release page

**Describe alternatives you've considered**
- sync codebase and build myself. But it’s more desirable to get all binaries out of the official build pipeline.

**Comment by linki** [comment]
@tnaroska I created a PR for an arm64 release [here](https://github.com/aelsabbahy/goss/pull/737). I would like to hear your thoughts on this.

**Comment by tnaroska** [comment]
Thanks for working on this @linki ! PR looks good to me.
My use case is AWS Graviton/Apple M1 only, so I cannot comment on the 32-bit arm part in install.sh.

**Comment by smwltr** [comment]
@linki Is there anything I can do to help? Do you need some testing done?

**Comment by linki** [comment]
@smwltr I just simplified https://github.com/aelsabbahy/goss/pull/737 and we can hopefully merge this soon. If you can test the resulting `goss-linux-arm` (should be 32-bit) and `goss-linux-arm64` (should be 64-bit) after we merged the PR, then that would be great.

If you have access to a 32-bit arm machine you could check its out for `uname -m` and we could add it to the `if` statement in https://github.com/aelsabbahy/goss/pull/756. Or if you're certain about the other possible values we could also just add them without confirming first.

**Comment by smwltr** [comment]
@linki I only have access to ARM64 machines, which gives: `aarch64`
