### ISSUE TITLE
test-kitchen plugin

### ISSUE THREAD

**Issue by ahelal** [aelsabbahy/goss#75]
Hey Ahmed,

Thanks again for great project. Though you might be interested I just created a test-kitchen plugin to use GOSS as a verifier. 

Regards
Adham

**Comment by aelsabbahy** [comment]
Awesome, how different is it from https://github.com/kisoku/busser-goss ?

**Comment by ahelal** [comment]
Does not require busser "no ruby" on target. So no ruby + docker friendly

**Comment by aelsabbahy** [comment]
Thanks for the explanation. I'll keep this issue open until I update the docs.

**Comment by aelsabbahy** [comment]
Added to readme, thanks for making this!
