### ISSUE TITLE
dgoss and vars parameter

### ISSUE THREAD

**Issue by bostrowski13** [aelsabbahy/goss#755]
tl;dr - can i use --vars with dgoss, and if so how?

I was wondering if its possible to use dgoss with the --vars param.  I have yaml files that contain configs my docker container is built with, but when i try to pass --vars to this it fails.

```
dgoss run --vars configenv/version1.yml -it myhub.test/my_image:latest /bin/bash 
unknown flag: --vars
See 'docker run --help'.
```

**Comment by aelsabbahy** [comment]
Let me know if this works for you:

https://github.com/aelsabbahy/goss/tree/master/extras/dgoss#goss_vars

**Comment by aelsabbahy** [comment]
Closing this out as answered. Feel free to open a new issue if it's not.
