### ISSUE TITLE
Update to more recent version of codegangsta/cli

### ISSUE THREAD

**Issue by siddharthist** [aelsabbahy/goss#77]
When updating `glide.yaml` to use `cli` version 1.2.0 and attempting to build `goss`, I get the following error:
```
# github.com/aelsabbahy/goss
../../add.go:19: c.Duration undefined (type *cli.Context has no field or method Duration)
../../validate.go:26: c.GlobalIsSet undefined (type *cli.Context has no field or method GlobalIsSet)
```
Distributive uses a more recent version, so I can't take advantage of certain paths in `goss` code until this is fixed. I'll look into it. 

For reference, the current pinned commit is from 2015:
```
$ git show 70e3fa51ebed95df8c0fbe1519c1c1f9bc16bb13
commit 70e3fa51ebed95df8c0fbe1519c1c1f9bc16bb13
Merge: f445c89 3463964
Author: Jesse Szwedko <jesse.szwedko@gmail.com>
Date:   Thu Oct 29 20:11:27 2015 -0700
```

**Comment by siddharthist** [comment]
Strangely, looks like `master` has those functions:
https://godoc.org/github.com/codegangsta/cli#Context.Duration

**Comment by aelsabbahy** [comment]
My recommendation would be to remove cli.Context from places it doesn't need to be.

So for example:
 ```
func (sys *System) detectPackage(c *cli.Context)
```
could be refactored as:
```
func (sys *System) detectPackage(forcePkg string)
```

* https://github.com/aelsabbahy/goss/blob/master/system/system.go#L89
