### ISSUE TITLE
UID is checked, even though it's not part of the definition

### ISSUE THREAD

**Issue by timstoop** [aelsabbahy/goss#8]
Hi,

This is the snippet I'm using:

    "user": {
        "sshd": {
            "exists": true,
            "gid": "65534",
            "groups": [
                "nogroup"
            ],
            "home": "/var/run/sshd"
        },

Which produces this error:

`User: sshd: uid: doesn't match, expect: [] found: [107]`

I would expect it to not check the uid at all.

**Comment by aelsabbahy** [comment]
Fixed in `v0.0.9`

**Comment by timstoop** [comment]
Nice turn around time :)
