### ISSUE TITLE
goss 0.1.6 requires doble 'enter' oressing to receive the result

### ISSUE THREAD

**Issue by taurus-forever** [aelsabbahy/goss#86]
Hi, 

Maybe I miss something or it is an issue with latest goss 0.1.6

STR:
> curl -L https://github.com/aelsabbahy/goss/releases/download/v0.1.6/goss-linux-amd64 > ./goss_0.1.6
> chmod a+x goss_0.1.6
> ./goss_0.1.6 --version # press ENTER

and nothing happens until I press the ENTER second time, after the second press I received the output:
> goss version v0.1.6

**Comment by aelsabbahy** [comment]
Weird, I'm not able to reproduce this, are you seeing it for all commands or just running `--version`?

**Comment by taurus-forever** [comment]
I cannot reproduce it anymore. I am sorry for the noise here.

**Comment by aelsabbahy** [comment]
No problem, I couldn't reproduce but didn't want to close the issue until I got feedback back from you. Glad you're no longer having the issue.
